// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXE14turW6m8Oh3JLOh73v2uH9zhI33F4',
    appId: '1:150463577498:web:eee17aebca8b7363468e23',
    messagingSenderId: '150463577498',
    projectId: 'nova-player-app',
    authDomain: 'nova-player-app.firebaseapp.com',
    storageBucket: 'nova-player-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUGjNAtHPciq5FE_qckwDOMoK1gGwZMM8',
    appId: '1:150463577498:android:6b92d2c902e502ed468e23',
    messagingSenderId: '150463577498',
    projectId: 'nova-player-app',
    storageBucket: 'nova-player-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAsTgs7tQEr7Sgg5J3lF4dVeiAPEEhkCM',
    appId: '1:150463577498:ios:d3b915b978ca290d468e23',
    messagingSenderId: '150463577498',
    projectId: 'nova-player-app',
    storageBucket: 'nova-player-app.firebasestorage.app',
    iosBundleId: 'com.kkmedia.mediaPlayer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAsTgs7tQEr7Sgg5J3lF4dVeiAPEEhkCM',
    appId: '1:150463577498:ios:d3b915b978ca290d468e23',
    messagingSenderId: '150463577498',
    projectId: 'nova-player-app',
    storageBucket: 'nova-player-app.firebasestorage.app',
    iosBundleId: 'com.kkmedia.mediaPlayer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXE14turW6m8Oh3JLOh73v2uH9zhI33F4',
    appId: '1:150463577498:web:86e3c17d97c10623468e23',
    messagingSenderId: '150463577498',
    projectId: 'nova-player-app',
    authDomain: 'nova-player-app.firebaseapp.com',
    storageBucket: 'nova-player-app.firebasestorage.app',
  );
}
