import 'package:flutter/cupertino.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

import '../blocs/local/local_bloc.dart';

class AppStrings {
  final Locale locale;

  AppStrings(this.locale);
  static const Map<String, Map<String, String>> translations = {
    'en': {
      'home': 'Home',
      'languageName': 'English',
      'video': 'Video',
      'videos': 'Videos',
      'audio': 'Audio',
      'settings': 'Settings',
      'theme': 'Theme',
      'language': 'English',
      'chooseLanguage': 'Choose the language',
      'selectPreferredLanguage':
      'Select your preferred language for accurate translation and smooth usage.',
      'welcome': 'Welcome',
      'organize': 'Organize',
      'skip': 'Skip',
      'favourite':'Favourite',
      'folder':'Folder',
      'items':"items",
      'videMusicPlayer':"Video & Music Player",
      "mediaPlayer":"MEDIA PLAYER",
      "addToFavourite":"Add to Favourite",
      "removeToFavourite":"Remove from Favourite",
      "delete":"Delete",
      "share":"Share",
      "showDetail":"Show detail",
      "addToPlaylist":"Add to playlist",
      "appTheme":"App Theme",
      "preferredLanguage":"Preferred Language",
      "shareTheApp":"Share the App",
      "rateTheApp":"Rate our app",
      "privacyPolicy":"Privacy Policy",


      "playlist":"Playlist",
      "noVideosFound":"No videos found",
      "noAudioFileFound":"No audio files found",
      "noFoldersFound":"No folders found",
      "searchVideos":"Search videos...",
      "noResultFound":"No results found",
      "mb":"MB",
      "cancel":"Cancel",
      "submit":"Submit",
      "showDetailPage":"Show detail page",
      "loading":"Loading...",
      "deleteMedia":"Delete media",
      "showThumb500":"Show 500 size thumb",
      "howWouldYouLove":"How would you Love this app?",
      "areYouSureWantDeleteThisFile?":"Are you sure you want to delete this file?",
    },

    'ar': {
      'home': 'الرئيسية',
      'languageName': 'Arabic',
      'video': 'فيديو',
      'videos': 'فيديوهات',
      'audio': 'صوت',
      'settings': 'الإعدادات',
      'theme': 'السمة',
      'language': 'العربية',
      'chooseLanguage': 'اختر اللغة',
      'selectPreferredLanguage': 'حدد لغتك المفضلة.',
      'welcome': 'مرحبا',
      'organize': 'تنظيم',
      'skip': 'تخطى',
      'favourite': 'المفضلة',
      'folder': 'مجلد',
      'items': 'عناصر',
      'videMusicPlayer': 'مشغل الفيديو والموسيقى',
      'mediaPlayer': 'مشغل الوسائط',
      'addToFavourite': 'إضافة إلى المفضلة',
      'removeToFavourite': 'إزالة من المفضلة',
      'delete': 'حذف',
      'share': 'مشاركة',
      'showDetail': 'عرض التفاصيل',
      'addToPlaylist': 'إضافة إلى قائمة التشغيل',
      'appTheme': 'ثيم التطبيق',
      'preferredLanguage': 'اللغة المفضلة',
      'shareTheApp': 'مشاركة التطبيق',
      'rateTheApp': 'تقييم التطبيق',
      'privacyPolicy': 'سياسة الخصوصية',
    },

    'my': {
      'home': 'ပင်မစာမျက်နှာ',
      'languageName': 'Burmese',
      'video': 'ဗီဒီယို',
      'videos': 'ဗီဒီယိုများ',
      'audio': 'အသံ',
      'settings': 'ဆက်တင်များ',
      'theme': 'အပြင်အဆင်',
      'language': 'မြန်မာ',
      'chooseLanguage': 'ဘာသာစကားရွေးချယ်ပါ',
      'selectPreferredLanguage': 'သင်နှစ်သက်သောဘာသာစကားကိုရွေးပါ',
      'welcome': 'ကြိုဆိုပါသည်',
      'organize': 'စီစဉ်ပါ',
      'skip': 'ကျော်ရန်',
      'favourite': 'အကြိုက်ဆုံး',
      'folder': 'ဖိုင်တွဲ',
      'items': 'အကြောင်းအရာများ',
      'videMusicPlayer': 'ဗီဒီယိုနှင့် တေးဂီတဖွင့်စက်',
      'mediaPlayer': 'မီဒီယာဖွင့်စက်',
      'addToFavourite': 'အကြိုက်ဆုံးသို့ထည့်ပါ',
      'removeToFavourite': 'အကြိုက်ဆုံးမှဖယ်ပါ',
      'delete': 'ဖျက်ပါ',
      'share': 'မျှဝေပါ',
      'showDetail': 'အသေးစိတ်ပြပါ',
      'addToPlaylist': 'ပလေးလစ်သို့ထည့်ပါ',
      'appTheme': 'အက်ပ်ဒီဇိုင်း',
      'preferredLanguage': 'နှစ်သက်ရာဘာသာစကား',
      'shareTheApp': 'အက်ပ်ကိုမျှဝေပါ',
      'rateTheApp': 'အက်ပ်ကိုအဆင့်သတ်မှတ်ပါ',
      'privacyPolicy': 'ကိုယ်ရေးကိုယ်တာမူဝါဒ',
    },

    'fil': {
      'home': 'Home',
      'languageName': 'Filipino',
      'video': 'Video',
      'videos': 'Mga Video',
      'audio': 'Audio',
      'settings': 'Mga Setting',
      'theme': 'Tema',
      'language': 'Filipino',
      'chooseLanguage': 'Pumili ng wika',
      'selectPreferredLanguage': 'Piliin ang nais mong wika.',
      'welcome': 'Maligayang pagdating',
      'organize': 'Ayusin',
      'skip': 'Laktawan',
      'favourite': 'Paborito',
      'folder': 'Folder',
      'items': 'mga item',
      'videMusicPlayer': 'Video at Music Player',
      'mediaPlayer': 'MEDIA PLAYER',
      'addToFavourite': 'Idagdag sa Paborito',
      'removeToFavourite': 'Alisin sa Paborito',
      'delete': 'Burahin',
      'share': 'Ibahagi',
      'showDetail': 'Ipakita ang detalye',
      'addToPlaylist': 'Idagdag sa playlist',
      'appTheme': 'Tema ng App',
      'preferredLanguage': 'Mas gustong Wika',
      'shareTheApp': 'Ibahagi ang App',
      'rateTheApp': 'I-rate ang App',
      'privacyPolicy': 'Patakaran sa Privacy',
    },

    'fr': {
      'home': 'Accueil',
      'languageName': 'French',
      'video': 'Vidéo',
      'videos': 'Vidéos',
      'audio': 'Audio',
      'settings': 'Paramètres',
      'theme': 'Thème',
      'language': 'Français',
      'chooseLanguage': 'Choisir la langue',
      'selectPreferredLanguage': 'Sélectionnez votre langue préférée.',
      'welcome': 'Bienvenue',
      'organize': 'Organiser',
      'skip': 'Passer',
      'favourite': 'Favoris',
      'folder': 'Dossier',
      'items': 'éléments',
      'videMusicPlayer': 'Lecteur Vidéo & Musique',
      'mediaPlayer': 'LECTEUR MÉDIA',
      'addToFavourite': 'Ajouter aux favoris',
      'removeToFavourite': 'Retirer des favoris',
      'delete': 'Supprimer',
      'share': 'Partager',
      'showDetail': 'Afficher les détails',
      'addToPlaylist': 'Ajouter à la playlist',
      'appTheme': 'Thème de l\'application',
      'preferredLanguage': 'Langue préférée',
      'shareTheApp': 'Partager l\'application',
      'rateTheApp': 'Noter l\'application',
      'privacyPolicy': 'Politique de confidentialité',
    },

    'de': {
      'home': 'Startseite',
      'languageName': 'German',
      'video': 'Video',
      'videos': 'Videos',
      'audio': 'Audio',
      'settings': 'Einstellungen',
      'theme': 'Thema',
      'language': 'Deutsch',
      'chooseLanguage': 'Sprache wählen',
      'selectPreferredLanguage': 'Bevorzugte Sprache auswählen.',
      'welcome': 'Willkommen',
      'organize': 'Organisieren',
      'skip': 'Überspringen',
      'favourite': 'Favoriten',
      'folder': 'Ordner',
      'items': 'Elemente',
      'videMusicPlayer': 'Video- & Musik-Player',
      'mediaPlayer': 'MEDIENPLAYER',
      'addToFavourite': 'Zu Favoriten hinzufügen',
      'removeToFavourite': 'Aus Favoriten entfernen',
      'delete': 'Löschen',
      'share': 'Teilen',
      'showDetail': 'Details anzeigen',
      'addToPlaylist': 'Zur Playlist hinzufügen',
      'appTheme': 'App-Design',
      'preferredLanguage': 'Bevorzugte Sprache',
      'shareTheApp': 'App teilen',
      'rateTheApp': 'App bewerten',
      'privacyPolicy': 'Datenschutzerklärung',
    },

    'gu': {
      'home': 'હોમ',
      'languageName': 'Gujarati',
      'video': 'વિડિયો',
      'videos': 'વિડિઓઝ',
      'audio': 'ઓડિયો',
      'settings': 'સેટિંગ્સ',
      'theme': 'થીમ',
      'language': 'ગુજરાતી',
      'chooseLanguage': 'ભાષા પસંદ કરો',
      'selectPreferredLanguage': 'તમારી પસંદની ભાષા પસંદ કરો.',
      'welcome': 'સ્વાગત છે',
      'organize': 'ગોઠવો',
      'skip': 'છોડી દો',
      'favourite': 'પસંદગીનું',
      'folder': 'ફોલ્ડર',
      'items': 'આઇટમ્સ',
      'videMusicPlayer': 'વીડિયો અને મ્યુઝિક પ્લેયર',
      'mediaPlayer': 'મીડિયા પ્લેયર',
      'addToFavourite': 'ફેવરિટમાં ઉમેરો',
      'removeToFavourite': 'ફેવરિટમાંથી દૂર કરો',
      'delete': 'કાઢી નાખો',
      'share': 'શેર કરો',
      'showDetail': 'વિગત બતાવો',
      'addToPlaylist': 'પ્લેલિસ્ટમાં ઉમેરો',
      'appTheme': 'એપ થીમ',
      'preferredLanguage': 'પસંદગીની ભાષા',
      'shareTheApp': 'એપ શેર કરો',
      'rateTheApp': 'એપને રેટ કરો',
      'privacyPolicy': 'પ્રાઇવસી પોલિસી',
    },

    'hi': {
      'home': 'होम',
      'languageName': 'Hindi',
      'video': 'वीडियो',
      'videos': 'वीडियो',
      'audio': 'ऑडियो',
      'settings': 'सेटिंग्स',
      'theme': 'थीम',
      'language': 'हिंदी',
      'chooseLanguage': 'भाषा चुनें',
      'selectPreferredLanguage': 'अपनी पसंदीदा भाषा चुनें।',
      'welcome': 'स्वागत है',
      'organize': 'व्यवस्थित करें',
      'skip': 'छोड़ें',
      'favourite': 'पसंदीदा',
      'folder': 'फ़ोल्डर',
      'items': 'आइटम',
      'videMusicPlayer': 'वीडियो और म्यूजिक प्लेयर',
      'mediaPlayer': 'मीडिया प्लेयर',
      'addToFavourite': 'पसंद में जोड़ें',
      'removeToFavourite': 'पसंद से हटाएं',
      'delete': 'मिटाएं',
      'share': 'साझा करें',
      'showDetail': 'विवरण दिखाएं',
      'addToPlaylist': 'प्लेलिस्ट में जोड़ें',
      'appTheme': 'ऐप थीम',
      'preferredLanguage': 'पसंदीदा भाषा',
      'shareTheApp': 'ऐप साझा करें',
      'rateTheApp': 'ऐप को रेट करें',
      'privacyPolicy': 'गोपनीयता नीति',
    },

    'id': {
      'home': 'Beranda',
      'languageName': 'Indonesian',
      'video': 'Video',
      'videos': 'Video',
      'audio': 'Audio',
      'settings': 'Pengaturan',
      'theme': 'Tema',
      'language': 'Indonesia',
      'chooseLanguage': 'Pilih bahasa',
      'selectPreferredLanguage': 'Pilih bahasa pilihan Anda.',
      'welcome': 'Selamat datang',
      'organize': 'Atur',
      'skip': 'Lewati',
      'favourite': 'Favorit',
      'folder': 'Folder',
      'items': 'item',
      'videMusicPlayer': 'Pemutar Video & Musik',
      'mediaPlayer': 'PEMUTAR MEDIA',
      'addToFavourite': 'Tambahkan ke Favorit',
      'removeToFavourite': 'Hapus dari Favorit',
      'delete': 'Hapus',
      'share': 'Bagikan',
      'showDetail': 'Tampilkan detail',
      'addToPlaylist': 'Tambah ke daftar putar',
      'appTheme': 'Tema Aplikasi',
      'preferredLanguage': 'Bahasa Pilihan',
      'shareTheApp': 'Bagikan Aplikasi',
      'rateTheApp': 'Beri nilai Aplikasi',
      'privacyPolicy': 'Kebijakan Privasi',
    },

    'it': {
      'home': 'Home',
      'languageName': 'Italian',
      'video': 'Video',
      'videos': 'Video',
      'audio': 'Audio',
      'settings': 'Impostazioni',
      'theme': 'Tema',
      'language': 'Italiano',
      'chooseLanguage': 'Scegli la lingua',
      'selectPreferredLanguage': 'Seleziona la lingua preferita.',
      'welcome': 'Benvenuto',
      'organize': 'Organizza',
      'skip': 'Salta',
      'favourite': 'Preferiti',
      'folder': 'Cartella',
      'items': 'elementi',
      'videMusicPlayer': 'Lettore Video e Musica',
      'mediaPlayer': 'LETTORE MULTIMEDIALE',
      'addToFavourite': 'Aggiungi ai preferiti',
      'removeToFavourite': 'Rimuovi dai preferiti',
      'delete': 'Elimina',
      'share': 'Condividi',
      'showDetail': 'Mostra dettagli',
      'addToPlaylist': 'Aggiungi alla playlist',
      'appTheme': 'Tema dell\'app',
      'preferredLanguage': 'Lingua preferita',
      'shareTheApp': 'Condividi l\'app',
      'rateTheApp': 'Valuta l\'app',
      'privacyPolicy': 'Informativa sulla privacy',
    },

    'ja': {
      'home': 'ホーム',
      'languageName': 'Japanese',
      'video': 'ビデオ',
      'videos': 'ビデオ',
      'audio': 'オーディオ',
      'settings': '設定',
      'theme': 'テーマ',
      'language': '日本語',
      'chooseLanguage': '言語を選択',
      'selectPreferredLanguage': '優先言語を選択してください。',
      'welcome': 'ようこそ',
      'organize': '整理',
      'skip': 'スキップ',
      'favourite': 'お気に入り',
      'folder': 'フォルダー',
      'items': 'アイテム',
      'videMusicPlayer': 'ビデオ＆音楽プレーヤー',
      'mediaPlayer': 'メディアプレーヤー',
      'addToFavourite': 'お気に入りに追加',
      'removeToFavourite': 'お気に入りから削除',
      'delete': '削除',
      'share': '共有',
      'showDetail': '詳細を表示',
      'addToPlaylist': 'プレイリストに追加',
      'appTheme': 'アプリのテーマ',
      'preferredLanguage': '優先言語',
      'shareTheApp': 'アプリを共有',
      'rateTheApp': 'アプリを評価',
      'privacyPolicy': 'プライバシーポリシー',
    },

    'ko': {
      'home': '홈',
      'languageName': 'Korean',
      'video': '비디오',
      'videos': '비디오',
      'audio': '오디오',
      'settings': '설정',
      'theme': '테마',
      'language': '한국어',
      'chooseLanguage': '언어 선택',
      'selectPreferredLanguage': '선호하는 언어를 선택하세요.',
      'welcome': '환영합니다',
      'organize': '정리',
      'skip': '건너뛰기',
      'favourite': '즐겨찾기',
      'folder': '폴더',
      'items': '항목',
      'videMusicPlayer': '비디오 및 음악 플레이어',
      'mediaPlayer': '미디어 플레이어',
      'addToFavourite': '즐겨찾기에 추가',
      'removeToFavourite': '즐겨찾기에서 제거',
      'delete': '삭제',
      'share': '공유',
      'showDetail': '상세 정보 보기',
      'addToPlaylist': '재생 목록에 추가',
      'appTheme': '앱 테마',
      'preferredLanguage': '선호하는 언어',
      'shareTheApp': '앱 공유',
      'rateTheApp': '앱 평가하기',
      'privacyPolicy': '개인정보 처리방침',
    },

    'ms': {
      'home': 'Laman Utama',
      'languageName': 'Malay',
      'video': 'Video',
      'videos': 'Video',
      'audio': 'Audio',
      'settings': 'Tetapan',
      'theme': 'Tema',
      'language': 'Melayu',
      'chooseLanguage': 'Pilih bahasa',
      'selectPreferredLanguage': 'Pilih bahasa pilihan anda.',
      'welcome': 'Selamat datang',
      'organize': 'Susun',
      'skip': 'Langkau',
      'favourite': 'Kegemaran',
      'folder': 'Folder',
      'items': 'item',
      'videMusicPlayer': 'Pemain Video & Muzik',
      'mediaPlayer': 'PEMAIN MEDIA',
      'addToFavourite': 'Tambah ke Kegemaran',
      'removeToFavourite': 'Alih dari Kegemaran',
      'delete': 'Padam',
      'share': 'Kongsi',
      'showDetail': 'Tunjukkan butiran',
      'addToPlaylist': 'Tambah ke senarai main',
      'appTheme': 'Tema Apl',
      'preferredLanguage': 'Bahasa Pilihan',
      'shareTheApp': 'Kongsi Apl',
      'rateTheApp': 'Nilai Apl',
      'privacyPolicy': 'Dasar Privasi',
    },

    'mr': {
      'home': 'मुख्यपृष्ठ',
      'languageName': 'Marathi',
      'video': 'व्हिडिओ',
      'videos': 'व्हिडिओ',
      'audio': 'ऑडिओ',
      'settings': 'सेटिंग्स',
      'theme': 'थीम',
      'language': 'मराठी',
      'chooseLanguage': 'भाषा निवडा',
      'selectPreferredLanguage': 'आपली पसंतीची भाषा निवडा.',
      'welcome': 'स्वागत आहे',
      'organize': 'व्यवस्थित करा',
      'skip': 'वगळा',
      'favourite': 'आवडते',
      'folder': 'फोल्डर',
      'items': 'आयटम',
      'videMusicPlayer': 'व्हिडिओ आणि म्युझિક प्लेयर',
      'mediaPlayer': 'मीडिया प्लेयर',
      'addToFavourite': 'आवडत्यामध्ये जोडा',
      'removeToFavourite': 'आवडत्यामधून काढा',
      'delete': 'हटवा',
      'share': 'शेअर करा',
      'showDetail': 'तपशील दाखवा',
      'addToPlaylist': 'प्लेलिस्टमध्ये जोडा',
      'appTheme': 'अ‍ॅप थीम',
      'preferredLanguage': 'पसंतीची भाषा',
      'shareTheApp': 'अ‍ॅप शेअर करा',
      'rateTheApp': 'अ‍ॅपला रेट करा',
      'privacyPolicy': 'गोपनीयता धोरण',
    },

    'fa': {
      'home': 'خانه',
      'languageName': 'Persian',
      'video': 'ویدیو',
      'videos': 'ویدیوها',
      'audio': 'صدا',
      'settings': 'تنظیمات',
      'theme': 'تم',
      'language': 'فارسی',
      'chooseLanguage': 'انتخاب زبان',
      'selectPreferredLanguage': 'زبان مورد نظر خود را انتخاب کنید.',
      'welcome': 'خوش آمدید',
      'organize': 'سازماندهی',
      'skip': 'رد کردن',
      'favourite': 'مورد علاقه',
      'folder': 'پوشه',
      'items': 'موارد',
      'videMusicPlayer': 'پخش‌کننده ویدیو و آهنگ',
      'mediaPlayer': 'پخش‌کننده رسانه',
      'addToFavourite': 'افزودن به مورد علاقه',
      'removeToFavourite': 'حذف از مورد علاقه',
      'delete': 'حذف',
      'share': 'اشتراک‌گذاری',
      'showDetail': 'نمایش جزئیات',
      'addToPlaylist': 'افزودن به لیست پخش',
      'appTheme': 'تم برنامه',
      'preferredLanguage': 'زبان مورد نظر',
      'shareTheApp': 'اشتراک‌گذاری برنامه',
      'rateTheApp': 'امتیاز به برنامه',
      'privacyPolicy': 'سیاست حریم خصوصی',
    },

    'pl': {
      'home': 'Strona główna',
      'languageName': 'Polish',
      'video': 'Wideo',
      'videos': 'Wideo',
      'audio': 'Audio',
      'settings': 'Ustawienia',
      'theme': 'Motyw',
      'language': 'Polski',
      'chooseLanguage': 'Wybierz język',
      'selectPreferredLanguage': 'Wybierz preferowany język.',
      'welcome': 'Witamy',
      'organize': 'Organizuj',
      'skip': 'Pomiń',
      'favourite': 'Ulubione',
      'folder': 'Folder',
      'items': 'elementy',
      'videMusicPlayer': 'Odtwarzacz wideo i muzyki',
      'mediaPlayer': 'ODTWARZACZ MULTIMEDIALNY',
      'addToFavourite': 'Dodaj do ulubionych',
      'removeToFavourite': 'Usuń z ulubionych',
      'delete': 'Usuń',
      'share': 'Udostępnij',
      'showDetail': 'Pokaż szczegóły',
      'addToPlaylist': 'Dodaj do playlisty',
      'appTheme': 'Motyw aplikacji',
      'preferredLanguage': 'Preferowany język',
      'shareTheApp': 'Udostępnij aplikację',
      'rateTheApp': 'Oceń aplikację',
      'privacyPolicy': 'Polityka prywatności',
    },

    'pt': {
      'home': 'Início',
      'languageName': 'Portuguese',
      'video': 'Vídeo',
      'videos': 'Vídeos',
      'audio': 'Áudio',
      'settings': 'Configurações',
      'theme': 'Tema',
      'language': 'Português',
      'chooseLanguage': 'Escolher idioma',
      'selectPreferredLanguage': 'Selecione o idioma preferido.',
      'welcome': 'Bem-vindo',
      'organize': 'Organizar',
      'skip': 'Pular',
      'favourite': 'Favoritos',
      'folder': 'Pasta',
      'items': 'itens',
      'videMusicPlayer': 'Player de Vídeo e Música',
      'mediaPlayer': 'REPRODUTOR MULTIMÍDIA',
      'addToFavourite': 'Adicionar aos favoritos',
      'removeToFavourite': 'Remover dos favoritos',
      'delete': 'Excluir',
      'share': 'Compartilhar',
      'showDetail': 'Mostrar detalhes',
      'addToPlaylist': 'Adicionar à playlist',
      'appTheme': 'Tema do aplicativo',
      'preferredLanguage': 'Idioma preferido',
      'shareTheApp': 'Compartilhar aplicativo',
      'rateTheApp': 'Avaliar o aplicativo',
      'privacyPolicy': 'Política de Privacidade',
    },

    'es': {
      'home': 'Inicio',
      'languageName': 'Spanish',
      'video': 'Video',
      'videos': 'Videos',
      'audio': 'Audio',
      'settings': 'Configuración',
      'theme': 'Tema',
      'language': 'Español',
      'chooseLanguage': 'Elegir idioma',
      'selectPreferredLanguage': 'Seleccione su idioma preferido.',
      'welcome': 'Bienvenido',
      'organize': 'Organizar',
      'skip': 'Omitir',
      'favourite': 'Favoritos',
      'folder': 'Carpeta',
      'items': 'elementos',
      'videMusicPlayer': 'Reproductor de Música y Video',
      'mediaPlayer': 'REPRODUCTOR MULTIMEDIA',
      'addToFavourite': 'Añadir a favoritos',
      'removeToFavourite': 'Eliminar de favoritos',
      'delete': 'Eliminar',
      'share': 'Compartir',
      'showDetail': 'Mostrar detalle',
      'addToPlaylist': 'Añadir a lista de reproducción',
      'appTheme': 'Tema de la aplicación',
      'preferredLanguage': 'Idioma preferido',
      'shareTheApp': 'Compartir la aplicación',
      'rateTheApp': 'Calificar la aplicación',
      'privacyPolicy': 'Política de privacidad',
    },

    'sv': {
      'home': 'Hem',
      'languageName': 'Swedish',
      'video': 'Video',
      'videos': 'Videor',
      'audio': 'Ljud',
      'settings': 'Inställningar',
      'theme': 'Tema',
      'language': 'Svenska',
      'chooseLanguage': 'Välj språk',
      'selectPreferredLanguage': 'Välj önskat språk.',
      'welcome': 'Välkommen',
      'organize': 'Organisera',
      'skip': 'Hoppa över',
      'favourite': 'Favorit',
      'folder': 'Mapp',
      'items': 'objekt',
      'videMusicPlayer': 'Video- och musikspelare',
      'mediaPlayer': 'MEDIASPELARE',
      'addToFavourite': 'Lägg till i favoriter',
      'removeToFavourite': 'Ta bort från favoriter',
      'delete': 'Radera',
      'share': 'Dela',
      'showDetail': 'Visa detaljer',
      'addToPlaylist': 'Lägg till i spellista',
      'appTheme': 'App-tema',
      'preferredLanguage': 'Föredraget språk',
      'shareTheApp': 'Dela appen',
      'rateTheApp': 'Betygsätt appen',
      'privacyPolicy': 'Integritetspolicy',
    },

    'ta': {
      'home': 'முகப்பு',
      'languageName': 'Tamil',
      'video': 'வீடியோ',
      'videos': 'வீடியோக்கள்',
      'audio': 'ஆடியோ',
      'settings': 'அமைப்புகள்',
      'theme': 'தீம்',
      'language': 'தமிழ்',
      'chooseLanguage': 'மொழியைத் தேர்ந்தெடுக்கவும்',
      'selectPreferredLanguage': 'உங்கள் விருப்பமான மொழியை தேர்ந்தெடுக்கவும்.',
      'welcome': 'வரவேற்கிறோம்',
      'organize': 'ஒழுங்குபடுத்து',
      'skip': 'தவிர்',
      'favourite': 'விருப்பமானவை',
      'folder': 'கோப்புறை',
      'items': 'உருப்படிகள்',
      'videMusicPlayer': 'வீடியோ மற்றும் இசை பிளேயர்',
      'mediaPlayer': 'மீடியா பிளேயர்',
      'addToFavourite': 'விருப்பத்தில் சேர்க்கவும்',
      'removeToFavourite': 'விருப்பத்திலிருந்து நீக்கவும்',
      'delete': 'நீக்கு',
      'share': 'பகிரவும்',
      'showDetail': 'விவரத்தைக் காட்டு',
      'addToPlaylist': 'பிளேலிஸ்ட்டில் சேர்க்க',
      'appTheme': 'பயன்பாட்டு தீம்',
      'preferredLanguage': 'விருப்பமான மொழி',
      'shareTheApp': 'செயலியைப் பகிரவும்',
      'rateTheApp': 'செயலியை மதிப்பிடவும்',
      'privacyPolicy': 'தனியுரிமைக் கொள்கை',
    },

    'ur': {
      'home': 'ہوم',
      'languageName': 'Urdu',
      'video': 'ویڈیو',
      'videos': 'ویڈیوز',
      'audio': 'آڈیو',
      'settings': 'ترتیبات',
      'theme': 'تھیم',
      'language': 'اردو',
      'chooseLanguage': 'زبان منتخب کریں',
      'selectPreferredLanguage': 'اپنی پسندیدہ زبان منتخب کریں۔',
      'welcome': 'خوش آمدید',
      'organize': 'ترتیب دیں',
      'skip': 'چھوڑیں',
      'favourite': 'پسندیدہ',
      'folder': 'فولڈر',
      'items': 'آئٹمز',
      'videMusicPlayer': 'ویڈیو اور میوزک پلیئر',
      'mediaPlayer': 'میڈیا پلیئر',
      'addToFavourite': 'پسندیدہ میں شامل کریں',
      'removeToFavourite': 'پسندیدہ سے ہٹائیں',
      'delete': 'حذف کریں',
      'share': 'شیئر کریں',
      'showDetail': 'تفصیل دکھائیں',
      'addToPlaylist': 'پلے لسٹ میں شامل کریں',
      'appTheme': 'ایپ تھیم',
      'preferredLanguage': 'پسندیدہ زبان',
      'shareTheApp': 'ایپ شیئر کریں',
      'rateTheApp': 'ایپ کی درجہ بندی کریں',
      'privacyPolicy': 'پرائیویسی پالیسی',
    },
  };

  String tr(String key) =>
      translations[locale.languageCode]?[key] ??
          translations['en']![key] ??
          key;

  static const LocalizationsDelegate<AppStrings> delegate = _AppLocDelegate();

  static String get(BuildContext context, String key) {
    final locale = Localizations.localeOf(context).languageCode;
    return translations[locale]?[key] ?? translations['en']![key] ?? key;
  }
}

class _AppLocDelegate extends LocalizationsDelegate<AppStrings> {
  const _AppLocDelegate();

  @override
  bool isSupported(Locale locale) =>
      AppStrings.translations.keys.contains(locale.languageCode);

  @override
  Future<AppStrings> load(Locale locale) async {
    return AppStrings(locale);
  }

  @override
  bool shouldReload(_AppLocDelegate old) => false;
}