import 'package:flutter/cupertino.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

import '../blocs/local/local_bloc.dart';

class AppStrings {
  final Locale locale;

  AppStrings(this.locale);
  static const Map<String, Map<String, String>> translations = {
    'en': {
      'home': 'Home',
      'languageName': 'English',
      'video': 'Video',
      'videos': 'Videos',
      'audio': 'Audio',
      'settings': 'Settings',
      'theme': 'Theme',
      'language': 'English',
      'chooseLanguage': 'Choose the language',
      'selectPreferredLanguage':
      'Select your preferred language for accurate translation and smooth usage.',
      'welcome': 'Welcome',
      'organize': 'Organize',
      'skip': 'Skip',
      'favourite': 'Favourite',
      'folder': 'Folder',
      'items': "items",
      'videMusicPlayer': "Video & Music Player",
      "mediaPlayer": "MEDIA PLAYER",
      "addToFavourite": "Add to Favourite",
      "removeToFavourite": "Remove from Favourite",
      "delete": "Delete",
      "share": "Share",
      "showDetail": "Show detail",
      "addToPlaylist": "Add to playlist",
      "appTheme": "App Theme",
      "preferredLanguage": "Preferred Language",
      "shareTheApp": "Share the App",
      "rateTheApp": "Rate our app",
      "privacyPolicy": "Privacy Policy",
      "otherSettings": "Other Settings",
      "playlist": "Playlist",
      "selectLanguage": "Select Language",
      "mediaPlayerApp": "Media Player",
      "noVideosFound": "No videos found",
      "noAudioFileFound": "No audio files found",
      "noFoldersFound": "No folders found",
      "searchVideos": "Search videos...",
      "noResultFound": "No results found",
      "mb": "MB",
      "yes": "Yes",
      "no": "No",
      "next": "Next",
      "done": "Done",
      "cancel": "Cancel",
      "submit": "Submit",
      "showDetailPage": "Show detail page",
      "loading": "Loading...",
      "deleteMedia": "Delete media",
      "exitApp": "Exit app?",
      "ohNoYouAreLeveApp": "Oh no! you are leave this application?",
      "showThumb500": "Show 500 size thumb",
      "howWouldYouLove": "How would you Love this app?",
      "areYouSureWantDeleteThisFile":
      "Are you sure you want to delete this file?",
      "searchAnything": "Search anything....",
      "deleteThisFile": "Delete this file?",
      "searchVideosAudios": "Search videos and audios",
      "noDataFound": "No Data found",
      "orCreateNew": "Or Create New",
      "enterName": "Enter Name",
      "add": "Add",
      "id": "id",
      "create": "Create",
      "modified": "Modified",
      "orientation": "Orientation",
      "size": "Size",
      "orientationSize": "Orientated Size",
      "duration": "Duration",
      "title": "Title",
      "relativePath": "Relative Path",
      "mimeType": "Mime Type",
      "rename": "Rename",
      "selectExistingPlaylist": "Select Existing Playlist",
      "choosePlaylist": "Choose Playlist",
      "newPlaylistCreated": "New Playlist Created",
      "pleaseSelectEnterPlaylistName": "Please select or enter playlist name",
      "alreadyExistIn": "Already exists in",
      "alreadyExists": "already exists",
      "addedTo": "Added to",
      "failedToDeleteFile": "Failed to delete file",
      "fileDeletedSuccessfully": "File deleted successfully",
      "errorSharingFile": "Error sharing file",
      "fileCanNotBeLoaded": "File cannot be loaded for sharing",
      "fileNotFound": "File not found or entity",
      "sharing": "Sharing:",
      "mediaFile:": "Media File",
      "addedToFavourite": "Added to Favourites",
      "removedFromFavourites": "Removed from Favourites",
    },
    'ar': {
      'home': 'الرئيسية',
      'languageName': 'Arabic',
      'video': 'فيديو',
      'videos': 'فيديوهات',
      'audio': 'صوت',
      'settings': 'الإعدادات',
      'theme': 'السمة',
      'language': 'العربية',
      'chooseLanguage': 'اختر اللغة',
      'selectPreferredLanguage': 'حدد لغتك المفضلة.',
      'welcome': 'مرحبا',
      'organize': 'تنظيم',
      'skip': 'تخطى',
      'favourite': 'المفضلة',
      'folder': 'مجلد',
      'items': 'عناصر',
      'videMusicPlayer': 'مشغل الفيديو والموسيقى',
      'mediaPlayer': 'مشغل الوسائط',
      'addToFavourite': 'إضافة إلى المفضلة',
      'removeToFavourite': 'إزالة من المفضلة',
      'delete': 'حذف',
      'share': 'مشاركة',
      'showDetail': 'عرض التفاصيل',
      'addToPlaylist': 'إضافة إلى قائمة التشغيل',
      'appTheme': 'ثيم التطبيق',
      'preferredLanguage': 'اللغة المفضلة',
      'shareTheApp': 'مشاركة التطبيق',
      'rateTheApp': 'تقييم التطبيق',
      'privacyPolicy': 'سياسة الخصوصية',
      "playlist": "قائمة التشغيل",
      "selectLanguage": "اختر اللغة",
      "mediaPlayerApp": "مشغل الوسائط",
      "noVideosFound": "لم يتم العثور على مقاطع فيديو",
      "noAudioFileFound": "لم يتم العثور على ملفات صوتية",
      "noFoldersFound": "لم يتم العثور على مجلدات",
      "searchVideos": "بحث عن مقاطع فيديو...",
      "noResultFound": "لم يتم العثور على نتائج",
      "mb": "ميغابايت",
      "yes": "نعم",
      "no": "لا",
      "next": "التالي",
      "done": "تم",
      "cancel": "إلغاء",
      "submit": "إرسال",
      "showDetailPage": "عرض صفحة التفاصيل",
      "loading": "جارٍ التحميل...",
      "deleteMedia": "حذف الوسائط",
      "exitApp": "الخروج من التطبيق؟",
      "ohNoYouAreLeveApp": "أوه لا! هل ستغادر هذا التطبيق؟",
      "showThumb500": "عرض مصغر بحجم 500",
      "howWouldYouLove": "كيف تقيم هذا التطبيق؟",
      "areYouSureWantDeleteThisFile": "هل أنت متأكد أنك تريد حذف هذا الملف؟",
      "searchAnything": "ابحث عن أي شيء....",
      "deleteThisFile": "حذف هذا الملف؟",
      "searchVideosAudios": "البحث عن الفيديوهات والتسجيلات الصوتية",
      "noDataFound": "لم يتم العثور على بيانات",
      "orCreateNew": "أو إنشاء جديد",
      "enterName": "أدخل الاسم",
      "add": "إضافة",
      "id": "المعرف",
      "create": "إنشاء",
      "modified": "تعديل",
      "orientation": "الاتجاه",
      "size": "الحجم",
      "orientationSize": "الحجم الموجه",
      "duration": "المدة",
      "title": "العنوان",
      "relativePath": "المسار النسبي",
      "mimeType": "نوع MIME",
      "rename": "إعادة تسمية",
      "selectExistingPlaylist": "اختر قائمة تشغيل موجودة",
      "choosePlaylist": "اختر قائمة تشغيل",
      "newPlaylistCreated": "تم إنشاء قائمة تشغيل جديدة",
      "pleaseSelectEnterPlaylistName": "يرجى اختيار أو إدخال اسم قائمة التشغيل",
      "alreadyExistIn": "موجود بالفعل في",
      "alreadyExists": "موجود بالفعل",
      "addedTo": "تمت إضافته إلى",
      "failedToDeleteFile": "فشل حذف الملف",
      "fileDeletedSuccessfully": "تم حذف الملف بنجاح",
      "errorSharingFile": "خطأ أثناء مشاركة الملف",
      "fileCanNotBeLoaded": "تعذر تحميل الملف للمشاركة",
      "fileNotFound": "الملف غير موجود",
      "sharing": "جاري المشاركة:",
      "mediaFile": "ملف وسائط",
      "addedToFavourite": "تمت الإضافة إلى المفضلة",
      "removedFromFavourites": "تمت الإزالة من المفضلة",
    },
    'my': {
      'home': 'ပင်မစာမျက်နှာ',
      'languageName': 'Burmese',
      'video': 'ဗီဒီယို',
      'videos': 'ဗီဒီယိုများ',
      'audio': 'အသံ',
      'settings': 'ဆက်တင်များ',
      'theme': 'အပြင်အဆင်',
      'language': 'မြန်မာ',
      'chooseLanguage': 'ဘာသာစကားရွေးချယ်ပါ',
      'selectPreferredLanguage': 'သင်နှစ်သက်သောဘာသာစကားကိုရွေးပါ',
      'welcome': 'ကြိုဆိုပါသည်',
      'organize': 'စီစဉ်ပါ',
      'skip': 'ကျော်ရန်',
      'favourite': 'အကြိုက်ဆုံး',
      'folder': 'ဖိုင်တွဲ',
      'items': 'အကြောင်းအရာများ',
      'videMusicPlayer': 'ဗီဒီယိုနှင့် တေးဂီတဖွင့်စက်',
      'mediaPlayer': 'မီဒီယာဖွင့်စက်',
      'addToFavourite': 'အကြိုက်ဆုံးသို့ထည့်ပါ',
      'removeToFavourite': 'အကြိုက်ဆုံးမှဖယ်ပါ',
      'delete': 'ဖျက်ပါ',
      'share': 'မျှဝေပါ',
      'showDetail': 'အသေးစိတ်ပြပါ',
      'addToPlaylist': 'ပလေးလစ်သို့ထည့်ပါ',
      'appTheme': 'အက်ပ်ဒီဇိုင်း',
      'preferredLanguage': 'နှစ်သက်ရာဘာသာစကား',
      'shareTheApp': 'အက်ပ်ကိုမျှဝေပါ',
      'rateTheApp': 'အက်ပ်ကိုအဆင့်သတ်မှတ်ပါ',
      'privacyPolicy': 'ကိုယ်ရေးကိုယ်တာမူဝါဒ',
      "playlist": "ဖွင့်ရန်စာရင်း",
      "selectLanguage": "ဘာသာစကားရွေးချယ်ပါ",
      "mediaPlayerApp": "မီဒီယာပလေယာ",
      "noVideosFound": "ဗီဒီယိုမတွေ့ပါ",
      "noAudioFileFound": "အသံဖိုင်မတွေ့ပါ",
      "noFoldersFound": "ဖိုင်တွဲမတွေ့ပါ",
      "searchVideos": "ဗီဒီယိုရှာရန်...",
      "noResultFound": "ရှာဖွေမှုရလဒ်မတွေ့ပါ",
      "mb": "MB",
      "yes": "ဟုတ်ကဲ့",
      "no": "မဟုတ်ပါ",
      "next": "နောက်သို့",
      "done": "ပြီးပြီ",
      "cancel": "ပယ်ဖျက်ရန်",
      "submit": "ပေးပို့ရန်",
      "showDetailPage": "အသေးစိတ်စာမျက်နှာကိုပြပါ",
      "loading": "လုပ်ဆောင်နေသည်...",
      "deleteMedia": "မီဒီယာကိုဖျက်ပါ",
      "exitApp": "အက်ပ်မှထွက်မလား?",
      "ohNoYouAreLeveApp": "မဟုတ်သေးဘူး! သင် ဒီအက်ပ်ကနေ ထွက်တော့မလို့လား?",
      "showThumb500": "ဆိုဒ် ၅၀၀ ရှိသော ပုံကိုပြပါ",
      "howWouldYouLove": "ဒီအက်ပ်ကို ဘယ်လောက်ကြိုက်လဲ?",
      "areYouSureWantDeleteThisFile": "ဒီဖိုင်ကို ဖျက်ရန် သေချာပါသလား?",
      "searchAnything": "တစ်ခုခုကိုရှာပါ....",
      "deleteThisFile": "ဒီဖိုင်ကို ဖျက်မလား?",
      "searchVideosAudios": "ဗီဒီယိုနှင့် အသံကို ရှာဖွေပါ",
      "noDataFound": "ဒေတာမတွေ့ပါ",
      "orCreateNew": "သို့မဟုတ် အသစ်ဖန်တီးပါ",
      "enterName": "အမည်ထည့်ပါ",
      "add": "ပေါင်းထည့်ရန်",
      "id": "ID",
      "create": "ဖန်တီးပါ",
      "modified": "ပြင်ဆင်သည့်ရက်စွဲ",
      "orientation": "မျက်နှာပြင်အနေအထား",
      "size": "အရွယ်အစား",
      "orientationSize": "အရွယ်အစားသတ်မှတ်ချက်",
      "duration": "ကြာချိန်",
      "title": "ခေါင်းစဉ်",
      "relativePath": "လမ်းကြောင်း",
      "mimeType": "ဖိုင်အမျိုးအစား",
      "rename": "အမည်ပြောင်းပါ",
      "selectExistingPlaylist": "ရှိပြီးသား ပလေးလစ်ကို ရွေးပါ",
      "choosePlaylist": "ပလေးလစ် ရွေးချယ်ရန်",
      "newPlaylistCreated": "ပလေးလစ် အသစ် ဖန်တီးပြီးပါပြီ",
      "pleaseSelectEnterPlaylistName":
      "ပလေးလစ် အမည် ရွေးပါ သို့မဟုတ် ရိုက်ထည့်ပါ",
      "alreadyExistIn": "ဤနေရာတွင် ရှိနှင့်ပြီးသားဖြစ်သည် -",
      "alreadyExists": "ရှိနှင့်ပြီးသားဖြစ်သည်",
      "addedTo": "ထဲသို့ ထည့်ပြီးပါပြီ",
      "failedToDeleteFile": "ဖိုင်ဖျက်ရန် မအောင်မြင်ပါ",
      "fileDeletedSuccessfully": "ဖိုင်ကို အောင်မြင်စွာ ဖျက်ပြီးပါပြီ",
      "errorSharingFile": "ဖိုင်မျှဝေရာတွင် အမှားအယွင်းရှိသည်",
      "fileCanNotBeLoaded": "မျှဝေရန် ဖိုင်ကို မဖွင့်နိုင်ပါ",
      "fileNotFound": "ဖိုင်ရှာမတွေ့ပါ",
      "sharing": "မျှဝေနေသည် -",
      "mediaFile": "မီဒီယာ ဖိုင်",
      "addedToFavourite": "အနှစ်သက်ဆုံးထဲသို့ ထည့်ပြီးပါပြီ",
      "removedFromFavourites": "အနှစ်သက်ဆုံးထဲမှ ဖယ်ရှားပြီးပါပြီ",
    },

    'fil': {
      'home': 'Home',
      'languageName': 'Filipino',
      'video': 'Video',
      'videos': 'Mga Video',
      'audio': 'Audio',
      'settings': 'Mga Setting',
      'theme': 'Tema',
      'language': 'Filipino',
      'chooseLanguage': 'Pumili ng wika',
      'selectPreferredLanguage': 'Piliin ang nais mong wika.',
      'welcome': 'Maligayang pagdating',
      'organize': 'Ayusin',
      'skip': 'Laktawan',
      'favourite': 'Paborito',
      'folder': 'Folder',
      'items': 'mga item',
      'videMusicPlayer': 'Video at Music Player',
      'mediaPlayer': 'MEDIA PLAYER',
      'addToFavourite': 'Idagdag sa Paborito',
      'removeToFavourite': 'Alisin sa Paborito',
      'delete': 'Burahin',
      'share': 'Ibahagi',
      'showDetail': 'Ipakita ang detalye',
      'addToPlaylist': 'Idagdag sa playlist',
      'appTheme': 'Tema ng App',
      'preferredLanguage': 'Mas gustong Wika',
      'shareTheApp': 'Ibahagi ang App',
      'rateTheApp': 'I-rate ang App',
      'privacyPolicy': 'Patakaran sa Privacy',
      "playlist": "Playlist",
      "selectLanguage": "Pumili ng Wika",
      "mediaPlayerApp": "Media Player",
      "noVideosFound": "Walang nakitang mga video",
      "noAudioFileFound": "Walang nakitang mga audio file",
      "noFoldersFound": "Walang nakitang mga folder",
      "searchVideos": "Maghanap ng mga video...",
      "noResultFound": "Walang nakitang resulta",
      "mb": "MB",
      "yes": "Oo",
      "no": "Hindi",
      "next": "Susunod",
      "done": "Tapos na",
      "cancel": "Kanselahin",
      "submit": "Isumite",
      "showDetailPage": "Ipakita ang pahina ng detalye",
      "loading": "Naglo-load...",
      "deleteMedia": "I-delete ang media",
      "exitApp": "Lalabas sa app?",
      "ohNoYouAreLeveApp": "Oh hindi! Aalis ka na ba sa application na ito?",
      "showThumb500": "Ipakita ang thumb size 500",
      "howWouldYouLove": "Gaano mo nagustuhan ang app na ito?",
      "areYouSureWantDeleteThisFile":
      "Sigurado ka bang gusto mong i-delete ang file na ito?",
      "searchAnything": "Maghanap ng kahit ano....",
      "deleteThisFile": "I-delete ang file na ito?",
      "searchVideosAudios": "Maghanap ng mga video at audio",
      "noDataFound": "Walang nakitang data",
      "orCreateNew": "O gumawa ng bago",
      "enterName": "Ilagay ang Pangalan",
      "add": "Idagdag",
      "id": "id",
      "create": "Gumawa",
      "modified": "Binago",
      "orientation": "Oryentasyon",
      "size": "Laki",
      "orientationSize": "Laki ng Oryentasyon",
      "duration": "Tagal",
      "title": "Pamagat",
      "relativePath": "Relative Path",
      "mimeType": "Mime Type",
      "rename": "Palitan ang Pangalan",
      "selectExistingPlaylist": "Pumili ng Umiiral na Playlist",
      "choosePlaylist": "Pumili ng Playlist",
      "newPlaylistCreated": "Bagong Playlist ay Nilikha",
      "pleaseSelectEnterPlaylistName":
      "Mangyaring pumili o magpasok ng pangalan ng playlist",
      "alreadyExistIn": "Umiiral na sa",
      "alreadyExists": "umiiral na",
      "addedTo": "Idinagdag sa",
      "failedToDeleteFile": "Bigo sa pagtanggal ng file",
      "fileDeletedSuccessfully": "Matagumpay na natanggal ang file",
      "errorSharingFile": "Error sa pagbabahagi ng file",
      "fileCanNotBeLoaded": "Hindi ma-load ang file para sa pagbabahagi",
      "fileNotFound": "Hindi nahanap ang file",
      "sharing": "Ibabahagi:",
      "mediaFile": "Media File",
      "addedToFavourite": "Idinagdag sa Mga Paborito",
      "removedFromFavourites": "Inalis sa Mga Paborito",
    },
    'fr': {
      'home': 'Accueil',
      'languageName': 'French',
      'video': 'Vidéo',
      'videos': 'Vidéos',
      'audio': 'Audio',
      'settings': 'Paramètres',
      'theme': 'Thème',
      'language': 'Français',
      'chooseLanguage': 'Choisir la langue',
      'selectPreferredLanguage': 'Sélectionnez votre langue préférée.',
      'welcome': 'Bienvenue',
      'organize': 'Organiser',
      'skip': 'Passer',
      'favourite': 'Favoris',
      'folder': 'Dossier',
      'items': 'éléments',
      'videMusicPlayer': 'Lecteur Vidéo & Musique',
      'mediaPlayer': 'LECTEUR MÉDIA',
      'addToFavourite': 'Ajouter aux favoris',
      'removeToFavourite': 'Retirer des favoris',
      'delete': 'Supprimer',
      'share': 'Partager',
      'showDetail': 'Afficher les détails',
      'addToPlaylist': 'Ajouter à la playlist',
      'appTheme': 'Thème de l\'application',
      'preferredLanguage': 'Langue préférée',
      'shareTheApp': 'Partager l\'application',
      'rateTheApp': 'Noter l\'application',
      'privacyPolicy': 'Politique de confidentialité',
      "playlist": "Liste de lecture",
      "selectLanguage": "Choisir la langue",
      "mediaPlayerApp": "Lecteur média",
      "noVideosFound": "Aucune vidéo trouvée",
      "noAudioFileFound": "Aucun fichier audio trouvé",
      "noFoldersFound": "Aucun dossier trouvé",
      "searchVideos": "Rechercher des vidéos...",
      "noResultFound": "Aucun résultat trouvé",
      "mb": "Mo",
      "yes": "Oui",
      "no": "Non",
      "next": "Suivant",
      "done": "Terminé",
      "cancel": "Annuler",
      "submit": "Envoyer",
      "showDetailPage": "Afficher la page de détails",
      "loading": "Chargement...",
      "deleteMedia": "Supprimer le média",
      "exitApp": "Quitter l'application ?",
      "ohNoYouAreLeveApp": "Oh non ! Vous quittez cette application ?",
      "showThumb500": "Afficher la miniature taille 500",
      "howWouldYouLove": "Comment aimez-vous cette application ?",
      "areYouSureWantDeleteThisFile":
      "Êtes-vous sûr de vouloir supprimer ce fichier ?",
      "searchAnything": "Rechercher n'importe quoi....",
      "deleteThisFile": "Supprimer ce fichier ?",
      "searchVideosAudios": "Rechercher des vidéos et des audios",
      "noDataFound": "Aucune donnée trouvée",
      "orCreateNew": "Ou créer un nouveau",
      "enterName": "Entrez le nom",
      "add": "Ajouter",
      "id": "id",
      "create": "Créer",
      "modified": "Modifié",
      "orientation": "Orientation",
      "size": "Taille",
      "orientationSize": "Taille orientée",
      "duration": "Durée",
      "title": "Titre",
      "relativePath": "Chemin relatif",
      "mimeType": "Type MIME",
      "rename": "Renommer",
      "selectExistingPlaylist": "Sélectionner une liste existante",
      "choosePlaylist": "Choisir une liste de lecture",
      "newPlaylistCreated": "Nouvelle liste de lecture créée",
      "pleaseSelectEnterPlaylistName": "Veuillez sélectionner ou saisir un nom",
      "alreadyExistIn": "Existe déjà dans",
      "alreadyExists": "existe déjà",
      "addedTo": "Ajouté à",
      "failedToDeleteFile": "Échec de la suppression du fichier",
      "fileDeletedSuccessfully": "Fichier supprimé avec succès",
      "errorSharingFile": "Erreur lors du partage du fichier",
      "fileCanNotBeLoaded": "Impossible de charger le fichier pour le partage",
      "fileNotFound": "Fichier non trouvé",
      "sharing": "Partage en cours :",
      "mediaFile": "Fichier multimédia",
      "addedToFavourite": "Ajouté aux favoris",
      "removedFromFavourites": "Supprimé des favoris",
    },
    'de': {
      'home': 'Startseite',
      'languageName': 'German',
      'video': 'Video',
      'videos': 'Videos',
      'audio': 'Audio',
      'settings': 'Einstellungen',
      'theme': 'Thema',
      'language': 'Deutsch',
      'chooseLanguage': 'Sprache wählen',
      'selectPreferredLanguage': 'Bevorzugte Sprache auswählen.',
      'welcome': 'Willkommen',
      'organize': 'Organisieren',
      'skip': 'Überspringen',
      'favourite': 'Favoriten',
      'folder': 'Ordner',
      'items': 'Elemente',
      'videMusicPlayer': 'Video- & Musik-Player',
      'mediaPlayer': 'MEDIENPLAYER',
      'addToFavourite': 'Zu Favoriten hinzufügen',
      'removeToFavourite': 'Aus Favoriten entfernen',
      'delete': 'Löschen',
      'share': 'Teilen',
      'showDetail': 'Details anzeigen',
      'addToPlaylist': 'Zur Playlist hinzufügen',
      'appTheme': 'App-Design',
      'preferredLanguage': 'Bevorzugte Sprache',
      'shareTheApp': 'App teilen',
      'rateTheApp': 'App bewerten',
      'privacyPolicy': 'Datenschutzerklärung',
      "playlist": "Playlist",
      "selectLanguage": "Sprache auswählen",
      "mediaPlayerApp": "Media Player",
      "noVideosFound": "Keine Videos gefunden",
      "noAudioFileFound": "Keine Audiodateien gefunden",
      "noFoldersFound": "Keine Ordner gefunden",
      "searchVideos": "Videos suchen...",
      "noResultFound": "Keine Ergebnisse gefunden",
      "mb": "MB",
      "yes": "Ja",
      "no": "Nein",
      "next": "Weiter",
      "done": "Fertig",
      "cancel": "Abbrechen",
      "submit": "Absenden",
      "showDetailPage": "Detailseite anzeigen",
      "loading": "Laden...",
      "deleteMedia": "Medien löschen",
      "exitApp": "App beenden?",
      "ohNoYouAreLeveApp": "Oh nein! Möchten Sie die App wirklich verlassen?",
      "showThumb500": "Vorschau in Größe 500 anzeigen",
      "howWouldYouLove": "Wie gefällt Ihnen diese App?",
      "areYouSureWantDeleteThisFile":
      "Sind Sie sicher, dass Sie diese Datei löschen möchten?",
      "searchAnything": "Alles suchen....",
      "deleteThisFile": "Diese Datei löschen?",
      "searchVideosAudios": "Videos und Audios suchen",
      "noDataFound": "Keine Daten gefunden",
      "orCreateNew": "Oder neu erstellen",
      "enterName": "Name eingeben",
      "add": "Hinzufügen",
      "id": "ID",
      "create": "Erstellen",
      "modified": "Geändert",
      "orientation": "Ausrichtung",
      "size": "Größe",
      "orientationSize": "Ausgerichtete Größe",
      "duration": "Dauer",
      "title": "Titel",
      "relativePath": "Relativer Pfad",
      "mimeType": "Mime-Typ",
      "rename": "Umbenennen",
      "selectExistingPlaylist": "Vorhandene Playlist auswählen",
      "choosePlaylist": "Playlist auswählen",
      "newPlaylistCreated": "Neue Playlist erstellt",
      "pleaseSelectEnterPlaylistName":
      "Bitte Playlist-Namen wählen oder eingeben",
      "alreadyExistIn": "Bereits vorhanden in",
      "alreadyExists": "existiert bereits",
      "addedTo": "Hinzugefügt zu",
      "failedToDeleteFile": "Datei konnte nicht gelöscht werden",
      "fileDeletedSuccessfully": "Datei erfolgreich gelöscht",
      "errorSharingFile": "Fehler beim Teilen der Datei",
      "fileCanNotBeLoaded": "Datei kann zum Teilen nicht geladen werden",
      "fileNotFound": "Datei nicht gefunden",
      "sharing": "Teilen:",
      "mediaFile": "Mediendatei",
      "addedToFavourite": "Zu Favoriten hinzugefügt",
      "removedFromFavourites": "Aus Favoriten entfernt",
    },
    'gu': {
      'home': 'હોમ',
      'languageName': 'Gujarati',
      'video': 'વિડિયો',
      'videos': 'વિડિઓઝ',
      'audio': 'ઓડિયો',
      'settings': 'સેટિંગ્સ',
      'theme': 'થીમ',
      'language': 'ગુજરાતી',
      'chooseLanguage': 'ભાષા પસંદ કરો',
      'selectPreferredLanguage': 'તમારી પસંદની ભાષા પસંદ કરો.',
      'welcome': 'સ્વાગત છે',
      'organize': 'ગોઠવો',
      'skip': 'છોડી દો',
      'favourite': 'પસંદગીનું',
      'folder': 'ફોલ્ડર',
      'items': 'આઇટમ્સ',
      'videMusicPlayer': 'વીડિયો અને મ્યુઝિક પ્લેયર',
      'mediaPlayer': 'મીડિયા પ્લેયર',
      'addToFavourite': 'ફેવરિટમાં ઉમેરો',
      'removeToFavourite': 'ફેવરિટમાંથી દૂર કરો',
      'delete': 'કાઢી નાખો',
      'share': 'શેર કરો',
      'showDetail': 'વિગત બતાવો',
      'addToPlaylist': 'પ્લેલિસ્ટમાં ઉમેરો',
      'appTheme': 'એપ થીમ',
      'preferredLanguage': 'પસંદગીની ભાષા',
      'shareTheApp': 'એપ શેર કરો',
      'rateTheApp': 'એપને રેટ કરો',
      'privacyPolicy': 'પ્રાઇવસી પોલિસી',
      "playlist": "પ્લેલિસ્ટ",
      "selectLanguage": "ભાષા પસંદ કરો",
      "mediaPlayerApp": "મીડિયા પ્લેયર",
      "noVideosFound": "કોઈ વિડિઓ મળ્યા નથી",
      "noAudioFileFound": "કોઈ ઓડિયો ફાઈલો મળી નથી",
      "noFoldersFound": "કોઈ ફોલ્ડર્સ મળ્યા નથી",
      "searchVideos": "વિડિઓ શોધો...",
      "noResultFound": "કોઈ પરિણામ મળ્યું નથી",
      "mb": "MB",
      "yes": "હા",
      "no": "ના",
      "next": "આગળ",
      "done": "થઈ ગયું",
      "cancel": "રદ કરો",
      "submit": "સબમિટ કરો",
      "showDetailPage": "વિગતવાર પેજ જુઓ",
      "loading": "લોડ થઈ રહ્યું છે...",
      "deleteMedia": "મીડિયા ડિલીટ કરો",
      "exitApp": "એપમાંથી બહાર નીકળવું છે?",
      "ohNoYouAreLeveApp": "અરે ના! શું તમે આ એપ્લિકેશન છોડી રહ્યા છો?",
      "showThumb500": "500 સાઈઝની થંબ બતાવો",
      "howWouldYouLove": "તમને આ એપ કેવી લાગી?",
      "areYouSureWantDeleteThisFile":
      "શું તમે ખરેખર આ ફાઈલ ડિલીટ કરવા માંગો છો?",
      "searchAnything": "કંઈપણ શોધો....",
      "deleteThisFile": "આ ફાઈલ ડિલીટ કરવી છે?",
      "searchVideosAudios": "વિડિઓ અને ઓડિયો શોધો",
      "noDataFound": "કોઈ ડેટા મળ્યો નથી",
      "orCreateNew": "અથવા નવું બનાવો",
      "enterName": "નામ દાખલ કરો",
      "add": "ઉમેરો",
      "id": "id",
      "create": "બનાવો",
      "modified": "સુધારેલ",
      "orientation": "ઓરિએન્ટેશન",
      "size": "કદ",
      "orientationSize": "ઓરિએન્ટેડ કદ",
      "duration": "સમયગાળો",
      "title": "શીર્ષક",
      "relativePath": "સાપેક્ષ પાથ",
      "mimeType": "માઈમ પ્રકાર",
      "rename": "નામ બદલો",
      "selectExistingPlaylist": "હાલની પ્લેલિસ્ટ પસંદ કરો",
      "choosePlaylist": "પ્લેલિસ્ટ પસંદ કરો",
      "newPlaylistCreated": "નવી પ્લેલિસ્ટ બનાવવામાં આવી",
      "pleaseSelectEnterPlaylistName":
      "કૃપા કરીને પ્લેલિસ્ટનું નામ પસંદ કરો અથવા લખો",
      "alreadyExistIn": "પહેલેથી જ આમાં છે:",
      "alreadyExists": "પહેલેથી જ અસ્તિત્વમાં છે",
      "addedTo": "આમાં ઉમેરવામાં આવ્યું:",
      "failedToDeleteFile": "ફાઇલ ડિલીટ કરવામાં નિષ્ફળ",
      "fileDeletedSuccessfully": "ફાઇલ સફળતાપૂર્વક ડિલીટ થઈ",
      "errorSharingFile": "ફાઇલ શેર કરવામાં ભૂલ આવી",
      "fileCanNotBeLoaded": "શેર કરવા માટે ફાઇલ લોડ કરી શકાતી નથી",
      "fileNotFound": "ફાઇલ મળી નથી",
      "sharing": "શેર કરી રહ્યાં છે:",
      "mediaFile": "મીડિયા ફાઇલ",
      "addedToFavourite": "ફેવરિટમાં ઉમેરવામાં આવ્યું",
      "removedFromFavourites": "ફેવરિટમાંથી દૂર કરવામાં આવ્યું",
    },

    'hi': {
      'home': 'होम',
      'languageName': 'Hindi',
      'video': 'वीडियो',
      'videos': 'वीडियो',
      'audio': 'ऑडियो',
      'settings': 'सेटिंग्स',
      'theme': 'थीम',
      'language': 'हिंदी',
      'chooseLanguage': 'भाषा चुनें',
      'selectPreferredLanguage': 'अपनी पसंदीदा भाषा चुनें।',
      'welcome': 'स्वागत है',
      'organize': 'व्यवस्थित करें',
      'skip': 'छोड़ें',
      'favourite': 'पसंदीदा',
      'folder': 'फ़ोल्डर',
      'items': 'आइटम',
      'videMusicPlayer': 'वीडियो और म्यूजिक प्लेयर',
      'mediaPlayer': 'मीडिया प्लेयर',
      'addToFavourite': 'पसंद में जोड़ें',
      'removeToFavourite': 'पसंद से हटाएं',
      'delete': 'मिटाएं',
      'share': 'साझा करें',
      'showDetail': 'विवरण दिखाएं',
      'addToPlaylist': 'प्लेलिस्ट में जोड़ें',
      'appTheme': 'ऐप थीम',
      'preferredLanguage': 'पसंदीदा भाषा',
      'shareTheApp': 'ऐप साझा करें',
      'rateTheApp': 'ऐप को रेट करें',
      'privacyPolicy': 'गोपनीयता नीति',
      "playlist": "प्लेलिस्ट",
      "selectLanguage": "भाषा चुनें",
      "mediaPlayerApp": "मीडिया प्लेयर",
      "noVideosFound": "कोई वीडियो नहीं मिला",
      "noAudioFileFound": "कोई ऑडियो फाइल नहीं मिली",
      "noFoldersFound": "कोई फोल्डर नहीं मिला",
      "searchVideos": "वीडियो खोजें...",
      "noResultFound": "कोई परिणाम नहीं मिला",
      "mb": "MB",
      "yes": "हाँ",
      "no": "नहीं",
      "next": "अगला",
      "done": "हो गया",
      "cancel": "रद्द करें",
      "submit": "जमा करें",
      "showDetailPage": "विवरण पेज दिखाएं",
      "loading": "लोड हो रहा है...",
      "deleteMedia": "मीडिया हटाएं",
      "exitApp": "ऐप से बाहर निकलें?",
      "ohNoYouAreLeveApp": "ओह नहीं! क्या आप इस एप्लिकेशन को छोड़ रहे हैं?",
      "showThumb500": "500 आकार का थंब दिखाएं",
      "howWouldYouLove": "आपको यह ऐप कैसा लगा?",
      "areYouSureWantDeleteThisFile":
      "क्या आप वाकई इस फाइल को हटाना चाहते हैं?",
      "searchAnything": "कुछ भी खोजें....",
      "deleteThisFile": "इस फाइल को हटाएं?",
      "searchVideosAudios": "वीडियो और ऑडियो खोजें",
      "noDataFound": "कोई डेटा नहीं मिला",
      "orCreateNew": "या नया बनाएं",
      "enterName": "नाम दर्ज करें",
      "add": "जोड़ें",
      "id": "आईडी",
      "create": "बनाएं",
      "modified": "संशोधित",
      "orientation": "अभिविन्यास",
      "size": "आकार",
      "orientationSize": "अभिविन्यस्त आकार",
      "duration": "अवधि",
      "title": "शीर्षक",
      "relativePath": "सापेक्ष पथ",
      "mimeType": "माईम प्रकार",
      "rename": "नाम बदलें",
      "selectExistingPlaylist": "मौजूदा प्लेलिस्ट चुनें",
      "choosePlaylist": "प्लेलिस्ट चुनें",
      "newPlaylistCreated": "नई प्लेलिस्ट बनाई गई",
      "pleaseSelectEnterPlaylistName":
      "कृपया प्लेलिस्ट का नाम चुनें या दर्ज करें",
      "alreadyExistIn": "पहले से ही इसमें मौजूद है:",
      "alreadyExists": "पहले से मौजूद है",
      "addedTo": "इसमें जोड़ा गया:",
      "failedToDeleteFile": "फ़ाइल हटाने में विफल",
      "fileDeletedSuccessfully": "फ़ાઇલ सफलतापूर्वक हटा दी गई",
      "errorSharingFile": "फ़ाइल साझा करने में त्रुटિ",
      "fileCanNotBeLoaded": "साझा करने के लिए फ़ाइल लोड नहीं की जा શકે",
      "fileNotFound": "फ़ाइल नहीं मिली",
      "sharing": "साझा कर रहे हैं:",
      "mediaFile": "मीडिया फ़ाइल",
      "addedToFavourite": "पसंदीदा में जोड़ा गया",
      "removedFromFavourites": "पसंदीदा से हटा दिया गया",
    },
    'id': {
      'home': 'Beranda',
      'languageName': 'Indonesian',
      'video': 'Video',
      'videos': 'Video',
      'audio': 'Audio',
      'settings': 'Pengaturan',
      'theme': 'Tema',
      'language': 'Indonesia',
      'chooseLanguage': 'Pilih bahasa',
      'selectPreferredLanguage': 'Pilih bahasa pilihan Anda.',
      'welcome': 'Selamat datang',
      'organize': 'Atur',
      'skip': 'Lewati',
      'favourite': 'Favorit',
      'folder': 'Folder',
      'items': 'item',
      'videMusicPlayer': 'Pemutar Video & Musik',
      'mediaPlayer': 'PEMUTAR MEDIA',
      'addToFavourite': 'Tambahkan ke Favorit',
      'removeToFavourite': 'Hapus dari Favorit',
      'delete': 'Hapus',
      'share': 'Bagikan',
      'showDetail': 'Tampilkan detail',
      'addToPlaylist': 'Tambah ke daftar putar',
      'appTheme': 'Tema Aplikasi',
      'preferredLanguage': 'Bahasa Pilihan',
      'shareTheApp': 'Bagikan Aplikasi',
      'rateTheApp': 'Beri nilai Aplikasi',
      'privacyPolicy': 'Kebijakan Privasi',
      "playlist": "Daftar putar",
      "selectLanguage": "Pilih Bahasa",
      "mediaPlayerApp": "Pemutar Media",
      "noVideosFound": "Video tidak ditemukan",
      "noAudioFileFound": "File audio tidak ditemukan",
      "noFoldersFound": "Folder tidak ditemukan",
      "searchVideos": "Cari video...",
      "noResultFound": "Hasil tidak ditemukan",
      "mb": "MB",
      "yes": "Ya",
      "no": "Tidak",
      "next": "Berikutnya",
      "done": "Selesai",
      "cancel": "Batal",
      "submit": "Kirim",
      "showDetailPage": "Tampilkan halaman detail",
      "loading": "Memuat...",
      "deleteMedia": "Hapus media",
      "exitApp": "Keluar dari aplikasi?",
      "ohNoYouAreLeveApp": "Oh tidak! Anda ingin meninggalkan aplikasi ini?",
      "showThumb500": "Tampilkan thumb ukuran 500",
      "howWouldYouLove": "Seberapa Anda menyukai aplikasi ini?",
      "areYouSureWantDeleteThisFile":
      "Apakah Anda yakin ingin menghapus file ini?",
      "searchAnything": "Cari apa saja....",
      "deleteThisFile": "Hapus file ini?",
      "searchVideosAudios": "Cari video dan audio",
      "noDataFound": "Data tidak ditemukan",
      "orCreateNew": "Atau buat baru",
      "enterName": "Masukkan Nama",
      "add": "Tambah",
      "id": "id",
      "create": "Buat",
      "modified": "Modifikasi",
      "orientation": "Orientasi",
      "size": "Ukuran",
      "orientationSize": "Ukuran Orientasi",
      "duration": "Durasi",
      "title": "Judul",
      "relativePath": "Jalur Relatif",
      "mimeType": "Tipe Mime",
      "rename": "Ubah Nama",
      "selectExistingPlaylist": "Pilih Daftar Putar yang Ada",
      "choosePlaylist": "Pilih Daftar Putar",
      "newPlaylistCreated": "Daftar Putar Baru Dibuat",
      "pleaseSelectEnterPlaylistName":
      "Silakan pilih atau masukkan nama daftar putar",
      "alreadyExistIn": "Sudah ada di",
      "alreadyExists": "sudah ada",
      "addedTo": "Ditambahkan ke",
      "failedToDeleteFile": "Gagal menghapus berkas",
      "fileDeletedSuccessfully": "Berkas berhasil dihapus",
      "errorSharingFile": "Kesalahan saat berbagi berkas",
      "fileCanNotBeLoaded": "Berkas tidak dapat dimuat untuk dibagikan",
      "fileNotFound": "Berkas tidak ditemukan",
      "sharing": "Berbagi:",
      "mediaFile": "Berkas Media",
      "addedToFavourite": "Ditambahkan ke Favorit",
      "removedFromFavourites": "Dihapus dari Favorit",
    },
    'it': {
      'home': 'Home',
      'languageName': 'Italian',
      'video': 'Video',
      'videos': 'Video',
      'audio': 'Audio',
      'settings': 'Impostazioni',
      'theme': 'Tema',
      'language': 'Italiano',
      'chooseLanguage': 'Scegli la lingua',
      'selectPreferredLanguage': 'Seleziona la lingua preferita.',
      'welcome': 'Benvenuto',
      'organize': 'Organizza',
      'skip': 'Salta',
      'favourite': 'Preferiti',
      'folder': 'Cartella',
      'items': 'elementi',
      'videMusicPlayer': 'Lettore Video e Musica',
      'mediaPlayer': 'LETTORE MULTIMEDIALE',
      'addToFavourite': 'Aggiungi ai preferiti',
      'removeToFavourite': 'Rimuovi dai preferiti',
      'delete': 'Elimina',
      'share': 'Condividi',
      'showDetail': 'Mostra dettagli',
      'addToPlaylist': 'Aggiungi alla playlist',
      'appTheme': 'Tema dell\'app',
      'preferredLanguage': 'Lingua preferita',
      'shareTheApp': 'Condividi l\'app',
      'rateTheApp': 'Valuta l\'app',
      'privacyPolicy': 'Informativa sulla privacy',
      "playlist": "Playlist",
      "selectLanguage": "Seleziona Lingua",
      "mediaPlayerApp": "Lettore multimediale",
      "noVideosFound": "Nessun video trovato",
      "noAudioFileFound": "Nessun file audio trovato",
      "noFoldersFound": "Nessuna cartella trovata",
      "searchVideos": "Cerca video...",
      "noResultFound": "Nessun risultato trovato",
      "mb": "MB",
      "yes": "Sì",
      "no": "No",
      "next": "Avanti",
      "done": "Fatto",
      "cancel": "Annulla",
      "submit": "Invia",
      "showDetailPage": "Mostra pagina dei dettagli",
      "loading": "Caricamento...",
      "deleteMedia": "Elimina media",
      "exitApp": "Uscire dall'app?",
      "ohNoYouAreLeveApp": "Oh no! Vuoi lasciare questa applicazione?",
      "showThumb500": "Mostra anteprima dimensione 500",
      "howWouldYouLove": "Quanto ti piace questa app?",
      "areYouSureWantDeleteThisFile":
      "Sei sicuro di voler eliminare questo file?",
      "searchAnything": "Cerca qualsiasi cosa....",
      "deleteThisFile": "Eliminare questo file?",
      "searchVideosAudios": "Cerca video e audio",
      "noDataFound": "Nessun dato trovato",
      "orCreateNew": "O crea nuovo",
      "enterName": "Inserisci nome",
      "add": "Aggiungi",
      "id": "id",
      "create": "Crea",
      "modified": "Modificato",
      "orientation": "Orientamento",
      "size": "Dimensione",
      "orientationSize": "Dimensione orientata",
      "duration": "Durata",
      "title": "Titolo",
      "relativePath": "Percorso relativo",
      "mimeType": "Tipo Mime",
      "rename": "Rinomina",
      "selectExistingPlaylist": "Seleziona Playlist Esistente",
      "choosePlaylist": "Scegli Playlist",
      "newPlaylistCreated": "Nuova Playlist Creata",
      "pleaseSelectEnterPlaylistName":
      "Seleziona o inserisci il nome della playlist",
      "alreadyExistIn": "Esiste già in",
      "alreadyExists": "esiste già",
      "addedTo": "Aggiunto a",
      "failedToDeleteFile": "Impossibile eliminare il file",
      "fileDeletedSuccessfully": "File eliminato con successo",
      "errorSharingFile": "Errore nella condivisione del file",
      "fileCanNotBeLoaded":
      "Il file non può essere caricato per la condivisione",
      "fileNotFound": "File non trovato",
      "sharing": "Condivisione:",
      "mediaFile": "File Multimediale",
      "addedToFavourite": "Aggiunto ai Preferiti",
      "removedFromFavourites": "Rimosso dai Preferiti",
    },
    'ja': {
      'home': 'ホーム',
      'languageName': 'Japanese',
      'video': 'ビデオ',
      'videos': 'ビデオ',
      'audio': 'オーディオ',
      'settings': '設定',
      'theme': 'テーマ',
      'language': '日本語',
      'chooseLanguage': '言語を選択',
      'selectPreferredLanguage': '優先言語を選択してください。',
      'welcome': 'ようこそ',
      'organize': '整理',
      'skip': 'スキップ',
      'favourite': 'お気に入り',
      'folder': 'フォルダー',
      'items': 'アイテム',
      'videMusicPlayer': 'ビデオ＆音楽プレーヤー',
      'mediaPlayer': 'メディアプレーヤー',
      'addToFavourite': 'お気に入りに追加',
      'removeToFavourite': 'お気に入りから削除',
      'delete': '削除',
      'share': '共有',
      'showDetail': '詳細を表示',
      'addToPlaylist': 'プレイリストに追加',
      'appTheme': 'アプリのテーマ',
      'preferredLanguage': '優先言語',
      'shareTheApp': 'アプリを共有',
      'rateTheApp': 'アプリを評価',
      'privacyPolicy': 'プライバシーポリシー',
      "playlist": "プレイリスト",
      "selectLanguage": "言語を選択",
      "mediaPlayerApp": "メディアプレーヤー",
      "noVideosFound": "動画が見つかりません",
      "noAudioFileFound": "オーディオファイルが見つかりません",
      "noFoldersFound": "フォルダが見つかりません",
      "searchVideos": "動画を検索...",
      "noResultFound": "結果が見つかりません",
      "mb": "MB",
      "yes": "はい",
      "no": "いいえ",
      "next": "次へ",
      "done": "完了",
      "cancel": "キャンセル",
      "submit": "送信",
      "showDetailPage": "詳細ページを表示",
      "loading": "読み込み中...",
      "deleteMedia": "メディアを削除",
      "exitApp": "アプリを終了しますか？",
      "ohNoYouAreLeveApp": "あぁ！アプリを終了してしまいますか？",
      "showThumb500": "サイズ500のサムネイルを表示",
      "howWouldYouLove": "このアプリはいかがですか？",
      "areYouSureWantDeleteThisFile": "このファイルを削除してもよろしいですか？",
      "searchAnything": "何でも検索....",
      "deleteThisFile": "このファイルを削除しますか？",
      "searchVideosAudios": "動画と音声を検索",
      "noDataFound": "データが見つかりません",
      "orCreateNew": "または新しく作成",
      "enterName": "名前を入力",
      "add": "追加",
      "id": "ID",
      "create": "作成",
      "modified": "更新日",
      "orientation": "方向",
      "size": "サイズ",
      "orientationSize": "方向サイズ",
      "duration": "再生時間",
      "title": "タイトル",
      "relativePath": "相対パス",
      "mimeType": "MIMEタイプ",
      "rename": "名前変更",
      "selectExistingPlaylist": "既存のプレイリストを選択",
      "choosePlaylist": "プレイリストを選択",
      "newPlaylistCreated": "新しいプレイリストが作成されました",
      "pleaseSelectEnterPlaylistName": "プレイリスト名を選択または入力してください",
      "alreadyExistIn": "既に存在します：",
      "alreadyExists": "既に存在します",
      "addedTo": "に追加されました：",
      "failedToDeleteFile": "ファイルの削除に失敗しました",
      "fileDeletedSuccessfully": "ファイルを正常に削除しました",
      "errorSharingFile": "ファイルの共有中にエラーが発生しました",
      "fileCanNotBeLoaded": "共有用のファイルを読み込めません",
      "fileNotFound": "ファイルが見つかりません",
      "sharing": "共有中：",
      "mediaFile": "メディアファイル",
      "addedToFavourite": "お気に入りに追加されました",
      "removedFromFavourites": "お気に入りから削除されました",
    },

    'ko': {
      'home': '홈',
      'languageName': 'Korean',
      'video': '비디오',
      'videos': '비디오',
      'audio': '오디오',
      'settings': '설정',
      'theme': '테마',
      'language': '한국어',
      'chooseLanguage': '언어 선택',
      'selectPreferredLanguage': '선호하는 언어를 선택하세요.',
      'welcome': '환영합니다',
      'organize': '정리',
      'skip': '건너뛰기',
      'favourite': '즐겨찾기',
      'folder': '폴더',
      'items': '항목',
      'videMusicPlayer': '비디오 및 음악 플레이어',
      'mediaPlayer': '미디어 플레이어',
      'addToFavourite': '즐겨찾기에 추가',
      'removeToFavourite': '즐겨찾기에서 제거',
      'delete': '삭제',
      'share': '공유',
      'showDetail': '상세 정보 보기',
      'addToPlaylist': '재생 목록에 추가',
      'appTheme': '앱 테마',
      'preferredLanguage': '선호하는 언어',
      'shareTheApp': '앱 공유',
      'rateTheApp': '앱 평가하기',
      'privacyPolicy': '개인정보 처리방침',
      "playlist": "재생목록",
      "selectLanguage": "언어 선택",
      "mediaPlayerApp": "미디어 플레이어",
      "noVideosFound": "동영상을 찾을 수 없습니다",
      "noAudioFileFound": "오디오 파일을 찾을 수 없습니다",
      "noFoldersFound": "폴더를 찾을 수 없습니다",
      "searchVideos": "동영상 검색...",
      "noResultFound": "검색 결과가 없습니다",
      "mb": "MB",
      "yes": "예",
      "no": "아니요",
      "next": "다음",
      "done": "완료",
      "cancel": "취소",
      "submit": "제출",
      "showDetailPage": "상세 페이지 보기",
      "loading": "로딩 중...",
      "deleteMedia": "미디어 삭제",
      "exitApp": "앱을 종료할까요?",
      "ohNoYouAreLeveApp": "안돼요! 정말 앱을 종료하시겠어요?",
      "showThumb500": "500 사이즈 썸네일 보기",
      "howWouldYouLove": "이 앱이 마음에 드시나요?",
      "areYouSureWantDeleteThisFile": "정말 이 파일을 삭제하시겠습니까?",
      "searchAnything": "무엇이든 검색....",
      "deleteThisFile": "이 파일을 삭제할까요?",
      "searchVideosAudios": "비디오 및 오디오 검색",
      "noDataFound": "데이터를 찾을 수 없습니다",
      "orCreateNew": "또는 새로 만들기",
      "enterName": "이름 입력",
      "add": "추가",
      "id": "ID",
      "create": "생성",
      "modified": "수정일",
      "orientation": "방향",
      "size": "크기",
      "orientationSize": "방향 크기",
      "duration": "길이",
      "title": "제목",
      "relativePath": "상대 경로",
      "mimeType": "MIME 유형",
      "rename": "이름 바꾸기",
      "selectExistingPlaylist": "기존 재생목록 선택",
      "choosePlaylist": "재생목록 선택",
      "newPlaylistCreated": "새 재생목록 생성됨",
      "pleaseSelectEnterPlaylistName": "재생목록 이름을 선택하거나 입력하세요",
      "alreadyExistIn": "이미 다음에 존재함:",
      "alreadyExists": "이미 존재합니다",
      "addedTo": "다음에 추가됨:",
      "failedToDeleteFile": "파일 삭제 실패",
      "fileDeletedSuccessfully": "파일이 성공적으로 삭제되었습니다",
      "errorSharingFile": "파일 공유 오류",
      "fileCanNotBeLoaded": "공유할 파일을 불러올 수 없습니다",
      "fileNotFound": "파일을 찾을 수 없습니다",
      "sharing": "공유 중:",
      "mediaFile": "미디어 파일",
      "addedToFavourite": "즐겨찾기에 추가됨",
      "removedFromFavourites": "즐겨찾기에서 제거됨",
    },
    'ms': {
      'home': 'Laman Utama',
      'languageName': 'Malay',
      'video': 'Video',
      'videos': 'Video',
      'audio': 'Audio',
      'settings': 'Tetapan',
      'theme': 'Tema',
      'language': 'Melayu',
      'chooseLanguage': 'Pilih bahasa',
      'selectPreferredLanguage': 'Pilih bahasa pilihan anda.',
      'welcome': 'Selamat datang',
      'organize': 'Susun',
      'skip': 'Langkau',
      'favourite': 'Kegemaran',
      'folder': 'Folder',
      'items': 'item',
      'videMusicPlayer': 'Pemain Video & Muzik',
      'mediaPlayer': 'PEMAIN MEDIA',
      'addToFavourite': 'Tambah ke Kegemaran',
      'removeToFavourite': 'Alih dari Kegemaran',
      'delete': 'Padam',
      'share': 'Kongsi',
      'showDetail': 'Tunjukkan butiran',
      'addToPlaylist': 'Tambah ke senarai main',
      'appTheme': 'Tema Apl',
      'preferredLanguage': 'Bahasa Pilihan',
      'shareTheApp': 'Kongsi Apl',
      'rateTheApp': 'Nilai Apl',
      'privacyPolicy': 'Dasar Privasi',
      "playlist": "Senarai main",
      "selectLanguage": "Pilih Bahasa",
      "mediaPlayerApp": "Pemain Media",
      "noVideosFound": "Tiada video ditemui",
      "noAudioFileFound": "Tiada fail audio ditemui",
      "noFoldersFound": "Tiada folder ditemui",
      "searchVideos": "Cari video...",
      "noResultFound": "Tiada hasil ditemui",
      "mb": "MB",
      "yes": "Ya",
      "no": "Tidak",
      "next": "Seterusnya",
      "done": "Selesai",
      "cancel": "Batal",
      "submit": "Hantar",
      "showDetailPage": "Tunjukkan halaman butiran",
      "loading": "Memuatkan...",
      "deleteMedia": "Padam media",
      "exitApp": "Keluar dari aplikasi?",
      "ohNoYouAreLeveApp": "Oh tidak! Anda ingin meninggalkan aplikasi ini?",
      "showThumb500": "Tunjukkan thumb saiz 500",
      "howWouldYouLove": "Sejauh mana anda menyukai aplikasi ini?",
      "areYouSureWantDeleteThisFile":
      "Adakah anda pasti mahu memadam fail ini?",
      "searchAnything": "Cari apa sahaja....",
      "deleteThisFile": "Padam fail ini?",
      "searchVideosAudios": "Cari video dan audio",
      "noDataFound": "Tiada data ditemui",
      "orCreateNew": "Atau cipta baru",
      "enterName": "Masukkan Nama",
      "add": "Tambah",
      "id": "id",
      "create": "Cipta",
      "modified": "Diubah suai",
      "orientation": "Orientasi",
      "size": "Saiz",
      "orientationSize": "Saiz Orientasi",
      "duration": "Tempoh",
      "title": "Tajuk",
      "relativePath": "Laluan Relatif",
      "mimeType": "Jenis Mime",
      "rename": "Tukar Nama",
      "selectExistingPlaylist": "Pilih Senarai Main Sedia Ada",
      "choosePlaylist": "Pilih Senarai Main",
      "newPlaylistCreated": "Senarai Main Baru Dicipta",
      "pleaseSelectEnterPlaylistName":
      "Sila pilih atau masukkan nama senarai main",
      "alreadyExistIn": "Sudah wujud dalam",
      "alreadyExists": "sudah wujud",
      "addedTo": "Ditambah ke",
      "failedToDeleteFile": "Gagal memadam fail",
      "fileDeletedSuccessfully": "Fail berjaya dipadam",
      "errorSharingFile": "Ralat berkongsi fail",
      "fileCanNotBeLoaded": "Fail tidak dapat dimuatkan untuk dikongsi",
      "fileNotFound": "Fail tidak ditemui",
      "sharing": "Berkongsi:",
      "mediaFile": "Fail Media",
      "addedToFavourite": "Ditambah ke Kegemaran",
      "removedFromFavourites": "Dikeluarkan dari Kegemaran",
    },
    'mr': {
      'home': 'मुख्यपृष्ठ',
      'languageName': 'Marathi',
      'video': 'व्हिडिओ',
      'videos': 'व्हिडिओ',
      'audio': 'ऑडिओ',
      'settings': 'सेटिंग्स',
      'theme': 'थीम',
      'language': 'मराठी',
      'chooseLanguage': 'भाषा निवडा',
      'selectPreferredLanguage': 'आपली पसंतीची भाषा निवडा.',
      'welcome': 'स्वागत आहे',
      'organize': 'व्यवस्थित करा',
      'skip': 'वगळा',
      'favourite': 'आवडते',
      'folder': 'फोल्डर',
      'items': 'आयटम',
      'videMusicPlayer': 'व्हिडिओ आणि म्युझિક प्लेयर',
      'mediaPlayer': 'मीडिया प्लेयर',
      'addToFavourite': 'आवडत्यामध्ये जोडा',
      'removeToFavourite': 'आवडत्यामधून काढा',
      'delete': 'हटवा',
      'share': 'शेअर करा',
      'showDetail': 'तपशील दाखवा',
      'addToPlaylist': 'प्लेलिस्टमध्ये जोडा',
      'appTheme': 'अ‍ॅप थीम',
      'preferredLanguage': 'पसंतीची भाषा',
      'shareTheApp': 'अ‍ॅप शेअर करा',
      'rateTheApp': 'अ‍ॅपला रेट करा',
      'privacyPolicy': 'गोपनीयता धोरण',
      "playlist": "प्लेलिस्ट",
      "selectLanguage": "भाषा निवडा",
      "mediaPlayerApp": "मीडिया प्लेयर",
      "noVideosFound": "कोणतेही व्हिडिओ आढळले नाहीत",
      "noAudioFileFound": "कोणतीही ऑडिओ फाईल आढळली नाही",
      "noFoldersFound": "कोणतेही फोल्डर आढळले नाहीत",
      "searchVideos": "व्हिडिओ शोधा...",
      "noResultFound": "निकाल आढळला नाही",
      "mb": "MB",
      "yes": "हो",
      "no": "नाही",
      "next": "पुढील",
      "done": "पूर्ण",
      "cancel": "रद्द करा",
      "submit": "सबमिट करा",
      "showDetailPage": "तपशील पेज दाखवा",
      "loading": "लोड होत आहे...",
      "deleteMedia": "मीडिया हटवा",
      "exitApp": "अ‍ॅपमधून बाहेर पडायचे?",
      "ohNoYouAreLeveApp": "अरे नाही! तुम्ही हे अ‍ॅप्लिकेशन सोडत आहात?",
      "showThumb500": "५०० आकाराचा थंब दाखवा",
      "howWouldYouLove": "तुम्हाला हे अ‍ॅप कसे वाटले?",
      "areYouSureWantDeleteThisFile":
      "तुम्हाला खात्री आहे की तुम्ही ही फाईल हटवू इच्छिता?",
      "searchAnything": "काहीही शोधा....",
      "deleteThisFile": "ही फाईल हटवायची?",
      "searchVideosAudios": "व्हिडिओ आणि ऑडिओ शोधा",
      "noDataFound": "डेटा आढळला नाही",
      "orCreateNew": "किंवा नवीन तयार करा",
      "enterName": "नाव प्रविष्ट करा",
      "add": "जोडा",
      "id": "आयडी",
      "create": "तयार करा",
      "modified": "सुधारित",
      "orientation": "ओरिएंटेशन",
      "size": "आकार",
      "orientationSize": "ओरिएंटेड आकार",
      "duration": "कालावधी",
      "title": "शीर्षक",
      "relativePath": "सापेक्ष पाथ",
      "mimeType": "माईम प्रकार",
      "rename": "नाव बदला",
      "selectExistingPlaylist": "विद्यमान प्लेलिस्ट निवडा",
      "choosePlaylist": "प्लेलिस्ट निवडा",
      "newPlaylistCreated": "नवीन प्लेलिस्ट तयार केली",
      "pleaseSelectEnterPlaylistName":
      "कृपया प्लेलिस्टचे नाव निवडा किंवा प्रविष्ट करा",
      "alreadyExistIn": "आधीच यामध्ये आहे:",
      "alreadyExists": "आधीच अस्तित्वात आहे",
      "addedTo": "मध्ये जोडले गेले:",
      "failedToDeleteFile": "फाइल हटवण्यात अयशस्वी",
      "fileDeletedSuccessfully": "फाइल यशस्वीरित्या हटवली",
      "errorSharingFile": "फाइल शेअर करताना त्रुटी आली",
      "fileCanNotBeLoaded": "शेअर करण्यासाठी फाइल लोड होऊ शकत नाही",
      "fileNotFound": "फाइल सापडली नाही",
      "sharing": "शेअर करत आहे:",
      "mediaFile": "मीडिया फाइल",
      "addedToFavourite": "पसंतीमध्ये जोडले",
      "removedFromFavourites": "पसंतीमधून काढले",
    },
    'fa': {
      'home': 'خانه',
      'languageName': 'Persian',
      'video': 'ویدیو',
      'videos': 'ویدیوها',
      'audio': 'صدا',
      'settings': 'تنظیمات',
      'theme': 'تم',
      'language': 'فارسی',
      'chooseLanguage': 'انتخاب زبان',
      'selectPreferredLanguage': 'زبان مورد نظر خود را انتخاب کنید.',
      'welcome': 'خوش آمدید',
      'organize': 'سازماندهی',
      'skip': 'رد کردن',
      'favourite': 'مورد علاقه',
      'folder': 'پوشه',
      'items': 'موارد',
      'videMusicPlayer': 'پخش‌کننده ویدیو و آهنگ',
      'mediaPlayer': 'پخش‌کننده رسانه',
      'addToFavourite': 'افزودن به مورد علاقه',
      'removeToFavourite': 'حذف از مورد علاقه',
      'delete': 'حذف',
      'share': 'اشتراک‌گذاری',
      'showDetail': 'نمایش جزئیات',
      'addToPlaylist': 'افزودن به لیست پخش',
      'appTheme': 'تم برنامه',
      'preferredLanguage': 'زبان مورد نظر',
      'shareTheApp': 'اشتراک‌گذاری برنامه',
      'rateTheApp': 'امتیاز به برنامه',
      'privacyPolicy': 'سیاست حریم خصوصی',
      "playlist": "لیست پخش",
      "selectLanguage": "انتخاب زبان",
      "mediaPlayerApp": "پخش‌کننده رسانه",
      "noVideosFound": "ویدیویی یافت نشد",
      "noAudioFileFound": "فایل صوتی یافت نشد",
      "noFoldersFound": "پوشه‌ای یافت نشد",
      "searchVideos": "جستجوی ویدیو...",
      "noResultFound": "نتیجه‌ای یافت نشد",
      "mb": "مگابایت",
      "yes": "بله",
      "no": "خیر",
      "next": "بعدی",
      "done": "انجام شد",
      "cancel": "لغو",
      "submit": "ارسال",
      "showDetailPage": "نمایش صفحه جزئیات",
      "loading": "در حال بارگذاری...",
      "deleteMedia": "حذف رسانه",
      "exitApp": "خروج از برنامه؟",
      "ohNoYouAreLeveApp": "اوه نه! آیا قصد دارید این برنامه را ترک کنید؟",
      "showThumb500": "نمایش تصویر بندانگشتی سایز 500",
      "howWouldYouLove": "چقدر این برنامه را دوست دارید؟",
      "areYouSureWantDeleteThisFile":
      "آیا مطمئن هستید که می‌خواهید این فایل را حذف کنید؟",
      "searchAnything": "جستجوی هر چیزی....",
      "deleteThisFile": "این فایل حذف شود؟",
      "searchVideosAudios": "جستجوی ویدیوها و فایل‌های صوتی",
      "noDataFound": "داده‌ای یافت نشد",
      "orCreateNew": "یا ایجاد جدید",
      "enterName": "نام را وارد کنید",
      "add": "افزودن",
      "id": "شناسه",
      "create": "ایجاد",
      "modified": "تغییر یافته",
      "orientation": "جهت",
      "size": "اندازه",
      "orientationSize": "اندازه جهت‌دار",
      "duration": "مدت زمان",
      "title": "عنوان",
      "relativePath": "مسیر نسبی",
      "mimeType": "نوع MIME",
      "rename": "تغییر نام",
      "selectExistingPlaylist": "انتخاب لیست پخش موجود",
      "choosePlaylist": "انتخاب لیست پخش",
      "newPlaylistCreated": "لیست پخش جدید ایجاد شد",
      "pleaseSelectEnterPlaylistName":
      "لطفاً نام لیست پخش را انتخاب یا وارد کنید",
      "alreadyExistIn": "از قبل موجود است در",
      "alreadyExists": "از قبل وجود دارد",
      "addedTo": "اضافه شد به",
      "failedToDeleteFile": "حذف فایل ناموفق بود",
      "fileDeletedSuccessfully": "فایل با موفقیت حذف شد",
      "errorSharingFile": "خطا در اشتراک‌گذاری فایل",
      "fileCanNotBeLoaded": "فایل برای اشتراک‌گذاری بارگذاری نمی‌شود",
      "fileNotFound": "فایل پیدا نشد",
      "sharing": "در حال اشتراک‌گذاری:",
      "mediaFile": "فایل رسانه‌ای",
      "addedToFavourite": "به علاقه‌مندی‌ها اضافه شد",
      "removedFromFavourites": "از علاقه‌مندی‌ها حذف شد",
    },

    'pl': {
      'home': 'Strona główna',
      'languageName': 'Polish',
      'video': 'Wideo',
      'videos': 'Wideo',
      'audio': 'Audio',
      'settings': 'Ustawienia',
      'theme': 'Motyw',
      'language': 'Polski',
      'chooseLanguage': 'Wybierz język',
      'selectPreferredLanguage': 'Wybierz preferowany język.',
      'welcome': 'Witamy',
      'organize': 'Organizuj',
      'skip': 'Pomiń',
      'favourite': 'Ulubione',
      'folder': 'Folder',
      'items': 'elementy',
      'videMusicPlayer': 'Odtwarzacz wideo i muzyki',
      'mediaPlayer': 'ODTWARZACZ MULTIMEDIALNY',
      'addToFavourite': 'Dodaj do ulubionych',
      'removeToFavourite': 'Usuń z ulubionych',
      'delete': 'Usuń',
      'share': 'Udostępnij',
      'showDetail': 'Pokaż szczegóły',
      'addToPlaylist': 'Dodaj do playlisty',
      'appTheme': 'Motyw aplikacji',
      'preferredLanguage': 'Preferowany język',
      'shareTheApp': 'Udostępnij aplikację',
      'rateTheApp': 'Oceń aplikację',
      'privacyPolicy': 'Polityka prywatności',
      "playlist": "Playlista",
      "selectLanguage": "Wybierz język",
      "mediaPlayerApp": "Odtwarzacz mediów",
      "noVideosFound": "Nie znaleziono filmów",
      "noAudioFileFound": "Nie znaleziono plików audio",
      "noFoldersFound": "Nie znaleziono folderów",
      "searchVideos": "Szukaj filmów...",
      "noResultFound": "Nie znaleziono wyników",
      "mb": "MB",
      "yes": "Tak",
      "no": "Nie",
      "next": "Dalej",
      "done": "Gotowe",
      "cancel": "Anuluj",
      "submit": "Prześlij",
      "showDetailPage": "Pokaż stronę szczegółów",
      "loading": "Ładowanie...",
      "deleteMedia": "Usuń multimedia",
      "exitApp": "Wyjść z aplikacji?",
      "ohNoYouAreLeveApp": "O nie! Opuszczasz tę aplikację?",
      "showThumb500": "Pokaż miniaturę o rozmiarze 500",
      "howWouldYouLove": "Jak bardzo podoba Ci się ta aplikacja?",
      "areYouSureWantDeleteThisFile": "Czy na pewno chcesz usunąć ten plik?",
      "searchAnything": "Szukaj czegokolwiek....",
      "deleteThisFile": "Usunąć ten plik?",
      "searchVideosAudios": "Szukaj filmów i dźwięków",
      "noDataFound": "Nie znaleziono danych",
      "orCreateNew": "Lub utwórz nowy",
      "enterName": "Wpisz nazwę",
      "add": "Dodaj",
      "id": "id",
      "create": "Utwórz",
      "modified": "Zmodyfikowano",
      "orientation": "Orientacja",
      "size": "Rozmiar",
      "orientationSize": "Rozmiar zorientowany",
      "duration": "Czas trwania",
      "title": "Tytuł",
      "relativePath": "Ścieżka względna",
      "mimeType": "Typ Mime",
      "rename": "Zmień nazwę",
      "selectExistingPlaylist": "Wybierz istniejącą playlistę",
      "choosePlaylist": "Wybierz playlistę",
      "newPlaylistCreated": "Utworzono nową playlistę",
      "pleaseSelectEnterPlaylistName": "Wybierz lub wprowadź nazwę playlisty",
      "alreadyExistIn": "Już istnieje w",
      "alreadyExists": "już istnieje",
      "addedTo": "Dodano do",
      "failedToDeleteFile": "Nie udało się usunąć pliku",
      "fileDeletedSuccessfully": "Plik usunięty pomyślnie",
      "errorSharingFile": "Błąd udostępniania pliku",
      "fileCanNotBeLoaded": "Nie można załadować pliku do udostępnienia",
      "fileNotFound": "Nie znaleziono pliku",
      "sharing": "Udostępnianie:",
      "mediaFile": "Plik multimedialny",
      "addedToFavourite": "Dodano do ulubionych",
      "removedFromFavourites": "Usunięto z ulubionych",
    },
    'pt': {
      'home': 'Início',
      'languageName': 'Portuguese',
      'video': 'Vídeo',
      'videos': 'Vídeos',
      'audio': 'Áudio',
      'settings': 'Configurações',
      'theme': 'Tema',
      'language': 'Português',
      'chooseLanguage': 'Escolher idioma',
      'selectPreferredLanguage': 'Selecione o idioma preferido.',
      'welcome': 'Bem-vindo',
      'organize': 'Organizar',
      'skip': 'Pular',
      'favourite': 'Favoritos',
      'folder': 'Pasta',
      'items': 'itens',
      'videMusicPlayer': 'Player de Vídeo e Música',
      'mediaPlayer': 'REPRODUTOR MULTIMÍDIA',
      'addToFavourite': 'Adicionar aos favoritos',
      'removeToFavourite': 'Remover dos favoritos',
      'delete': 'Excluir',
      'share': 'Compartilhar',
      'showDetail': 'Mostrar detalhes',
      'addToPlaylist': 'Adicionar à playlist',
      'appTheme': 'Tema do aplicativo',
      'preferredLanguage': 'Idioma preferido',
      'shareTheApp': 'Compartilhar aplicativo',
      'rateTheApp': 'Avaliar o aplicativo',
      'privacyPolicy': 'Política de Privacidade',
      "playlist": "Lista de reprodução",
      "selectLanguage": "Selecionar Idioma",
      "mediaPlayerApp": "Reprodutor de Mídia",
      "noVideosFound": "Nenhum vídeo encontrado",
      "noAudioFileFound": "Nenhum arquivo de áudio encontrado",
      "noFoldersFound": "Nenhuma pasta encontrada",
      "searchVideos": "Pesquisar vídeos...",
      "noResultFound": "Nenhum resultado encontrado",
      "mb": "MB",
      "yes": "Sim",
      "no": "Não",
      "next": "Próximo",
      "done": "Concluído",
      "cancel": "Cancelar",
      "submit": "Enviar",
      "showDetailPage": "Mostrar página de detalhes",
      "loading": "Carregando...",
      "deleteMedia": "Excluir mídia",
      "exitApp": "Sair do aplicativo?",
      "ohNoYouAreLeveApp": "Oh não! Você está saindo deste aplicativo?",
      "showThumb500": "Mostrar miniatura tamanho 500",
      "howWouldYouLove": "O quanto você gosta deste aplicativo?",
      "areYouSureWantDeleteThisFile":
      "Tem certeza de que deseja excluir este arquivo?",
      "searchAnything": "Pesquisar qualquer coisa....",
      "deleteThisFile": "Excluir este arquivo?",
      "searchVideosAudios": "Pesquisar vídeos e áudios",
      "noDataFound": "Nenhum dado encontrado",
      "orCreateNew": "Ou criar novo",
      "enterName": "Digite o Nome",
      "add": "Adicionar",
      "id": "id",
      "create": "Criar",
      "modified": "Modificado",
      "orientation": "Orientação",
      "size": "Tamanho",
      "orientationSize": "Tamanho Orientado",
      "duration": "Duração",
      "title": "Título",
      "relativePath": "Caminho Relativo",
      "mimeType": "Tipo Mime",
      "rename": "Renomear",
      "selectExistingPlaylist": "Selecionar Playlist Existente",
      "choosePlaylist": "Escolher Playlist",
      "newPlaylistCreated": "Nova Playlist Criada",
      "pleaseSelectEnterPlaylistName":
      "Por favor, selecione ou insira o nome da playlist",
      "alreadyExistIn": "Já existe em",
      "alreadyExists": "já existe",
      "addedTo": "Adicionado a",
      "failedToDeleteFile": "Falha ao excluir arquivo",
      "fileDeletedSuccessfully": "Arquivo excluído com sucesso",
      "errorSharingFile": "Erro ao compartilhar arquivo",
      "fileCanNotBeLoaded":
      "O arquivo não pode ser carregado para compartilhamento",
      "fileNotFound": "Arquivo não encontrado",
      "sharing": "Compartilhando:",
      "mediaFile": "Arquivo de Mídia",
      "addedToFavourite": "Adicionado aos Favoritos",
      "removedFromFavourites": "Removido dos Favoritos",
    },
    'es': {
      'home': 'Inicio',
      'languageName': 'Spanish',
      'video': 'Video',
      'videos': 'Videos',
      'audio': 'Audio',
      'settings': 'Configuración',
      'theme': 'Tema',
      'language': 'Español',
      'chooseLanguage': 'Elegir idioma',
      'selectPreferredLanguage': 'Seleccione su idioma preferido.',
      'welcome': 'Bienvenido',
      'organize': 'Organizar',
      'skip': 'Omitir',
      'favourite': 'Favoritos',
      'folder': 'Carpeta',
      'items': 'elementos',
      'videMusicPlayer': 'Reproductor de Música y Video',
      'mediaPlayer': 'REPRODUCTOR MULTIMEDIA',
      'addToFavourite': 'Añadir a favoritos',
      'removeToFavourite': 'Eliminar de favoritos',
      'delete': 'Eliminar',
      'share': 'Compartir',
      'showDetail': 'Mostrar detalle',
      'addToPlaylist': 'Añadir a lista de reproducción',
      'appTheme': 'Tema de la aplicación',
      'preferredLanguage': 'Idioma preferido',
      'shareTheApp': 'Compartir la aplicación',
      'rateTheApp': 'Calificar la aplicación',
      'privacyPolicy': 'Política de privacidad',
      "playlist": "Lista de reproducción",
      "selectLanguage": "Seleccionar idioma",
      "mediaPlayerApp": "Reproductor de medios",
      "noVideosFound": "No se encontraron videos",
      "noAudioFileFound": "No se encontraron archivos de audio",
      "noFoldersFound": "No se encontraron carpetas",
      "searchVideos": "Buscar videos...",
      "noResultFound": "No se encontraron resultados",
      "mb": "MB",
      "yes": "Sí",
      "no": "No",
      "next": "Siguiente",
      "done": "Hecho",
      "cancel": "Cancelar",
      "submit": "Enviar",
      "showDetailPage": "Mostrar página de detalles",
      "loading": "Cargando...",
      "deleteMedia": "Eliminar medios",
      "exitApp": "¿Salir de la aplicación?",
      "ohNoYouAreLeveApp": "¡Oh no! ¿Vas a dejar esta aplicación?",
      "showThumb500": "Mostrar miniatura tamaño 500",
      "howWouldYouLove": "¿Qué te parece esta aplicación?",
      "areYouSureWantDeleteThisFile":
      "¿Estás seguro de que quieres eliminar este archivo?",
      "searchAnything": "Buscar cualquier cosa....",
      "deleteThisFile": "¿Eliminar este archivo?",
      "searchVideosAudios": "Buscar videos y audios",
      "noDataFound": "No se encontraron datos",
      "orCreateNew": "O crear uno nuevo",
      "enterName": "Ingrese el nombre",
      "add": "Añadir",
      "id": "id",
      "create": "Crear",
      "modified": "Modificado",
      "orientation": "Orientación",
      "size": "Tamaño",
      "orientationSize": "Tamaño orientado",
      "duration": "Duración",
      "title": "Título",
      "relativePath": "Ruta relativa",
      "mimeType": "Tipo MIME",
      "rename": "Renombrar",
      "selectExistingPlaylist": "Seleccionar lista existente",
      "choosePlaylist": "Elegir lista de reproducción",
      "newPlaylistCreated": "Nueva lista creada",
      "pleaseSelectEnterPlaylistName":
      "Por favor seleccione o ingrese un nombre",
      "alreadyExistIn": "Ya existe en",
      "alreadyExists": "ya existe",
      "addedTo": "Agregado a",
      "failedToDeleteFile": "Error al eliminar archivo",
      "fileDeletedSuccessfully": "Archivo eliminado con éxito",
      "errorSharingFile": "Error al compartir archivo",
      "fileCanNotBeLoaded": "No se puede cargar el archivo",
      "fileNotFound": "Archivo no encontrado",
      "sharing": "Compartiendo:",
      "mediaFile": "Archivo multimedia",
      "addedToFavourite": "Agregado a favoritos",
      "removedFromFavourites": "Eliminado de favoritos",
    },
    'sv': {
      'home': 'Hem',
      'languageName': 'Swedish',
      'video': 'Video',
      'videos': 'Videor',
      'audio': 'Ljud',
      'settings': 'Inställningar',
      'theme': 'Tema',
      'language': 'Svenska',
      'chooseLanguage': 'Välj språk',
      'selectPreferredLanguage': 'Välj önskat språk.',
      'welcome': 'Välkommen',
      'organize': 'Organisera',
      'skip': 'Hoppa över',
      'favourite': 'Favorit',
      'folder': 'Mapp',
      'items': 'objekt',
      'videMusicPlayer': 'Video- och musikspelare',
      'mediaPlayer': 'MEDIASPELARE',
      'addToFavourite': 'Lägg till i favoriter',
      'removeToFavourite': 'Ta bort från favoriter',
      'delete': 'Radera',
      'share': 'Dela',
      'showDetail': 'Visa detaljer',
      'addToPlaylist': 'Lägg till i spellista',
      'appTheme': 'App-tema',
      'preferredLanguage': 'Föredraget språk',
      'shareTheApp': 'Dela appen',
      'rateTheApp': 'Betygsätt appen',
      'privacyPolicy': 'Integritetspolicy',
      "playlist": "Spellista",
      "selectLanguage": "Välj språk",
      "mediaPlayerApp": "Mediaspelare",
      "noVideosFound": "Inga videor hittades",
      "noAudioFileFound": "Inga ljudfiler hittades",
      "noFoldersFound": "Inga mappar hittades",
      "searchVideos": "Sök videor...",
      "noResultFound": "Inga resultat hittades",
      "mb": "MB",
      "yes": "Ja",
      "no": "Nej",
      "next": "Nästa",
      "done": "Klar",
      "cancel": "Avbryt",
      "submit": "Skicka",
      "showDetailPage": "Visa detaljsida",
      "loading": "Laddar...",
      "deleteMedia": "Radera media",
      "exitApp": "Avsluta appen?",
      "ohNoYouAreLeveApp": "Oh nej! Lämnar du den här applikationen?",
      "showThumb500": "Visa miniatyr storlek 500",
      "howWouldYouLove": "Hur mycket gillar du den här appen?",
      "areYouSureWantDeleteThisFile":
      "Är du säker på att du vill radera den här filen?",
      "searchAnything": "Sök vad som helst....",
      "deleteThisFile": "Radera den här filen?",
      "searchVideosAudios": "Sök videor och ljud",
      "noDataFound": "Inga data hittades",
      "orCreateNew": "Eller skapa ny",
      "enterName": "Ange namn",
      "add": "Lägg till",
      "id": "id",
      "create": "Skapa",
      "modified": "Ändrad",
      "orientation": "Orientering",
      "size": "Storlek",
      "orientationSize": "Orienterad storlek",
      "duration": "Längd",
      "title": "Titel",
      "relativePath": "Relativ sökväg",
      "mimeType": "Mime-typ",
      "rename": "Byt namn",
      "selectExistingPlaylist": "Välj befintlig spellista",
      "choosePlaylist": "Välj spellista",
      "newPlaylistCreated": "Ny spellista skapad",
      "pleaseSelectEnterPlaylistName": "Välj eller ange spellistans namn",
      "alreadyExistIn": "Finns redan i",
      "alreadyExists": "finns redan",
      "addedTo": "Tillagd i",
      "failedToDeleteFile": "Misslyckades med att radera filen",
      "fileDeletedSuccessfully": "Filen raderades framgångsrikt",
      "errorSharingFile": "Fel vid delning av fil",
      "fileCanNotBeLoaded": "Filen kan inte laddas för delning",
      "fileNotFound": "Filen hittades inte",
      "sharing": "Delar:",
      "mediaFile": "Mediafil",
      "addedToFavourite": "Tillagd i favoriter",
      "removedFromFavourites": "Borttagen från favoriter",
    },

    'ta': {
      'home': 'முகப்பு',
      'languageName': 'Tamil',
      'video': 'வீடியோ',
      'videos': 'வீடியோக்கள்',
      'audio': 'ஆடியோ',
      'settings': 'அமைப்புகள்',
      'theme': 'தீம்',
      'language': 'தமிழ்',
      'chooseLanguage': 'மொழியைத் தேர்ந்தெடுக்கவும்',
      'selectPreferredLanguage': 'உங்கள் விருப்பமான மொழியை தேர்ந்தெடுக்கவும்.',
      'welcome': 'வரவேற்கிறோம்',
      'organize': 'ஒழுங்குபடுத்து',
      'skip': 'தவிர்',
      'favourite': 'விருப்பமானவை',
      'folder': 'கோப்புறை',
      'items': 'உருப்படிகள்',
      'videMusicPlayer': 'வீடியோ மற்றும் இசை பிளேயர்',
      'mediaPlayer': 'மீடியா பிளேயர்',
      'addToFavourite': 'விருப்பத்தில் சேர்க்கவும்',
      'removeToFavourite': 'விருப்பத்திலிருந்து நீக்கவும்',
      'delete': 'நீக்கு',
      'share': 'பகிரவும்',
      'showDetail': 'விவரத்தைக் காட்டு',
      'addToPlaylist': 'பிளேலிஸ்ட்டில் சேர்க்க',
      'appTheme': 'பயன்பாட்டு தீம்',
      'preferredLanguage': 'விருப்பமான மொழி',
      'shareTheApp': 'செயலியைப் பகிரவும்',
      'rateTheApp': 'செயலியை மதிப்பிடவும்',
      'privacyPolicy': 'தனியுரிமைக் கொள்கை',
      "playlist": "பிளேலிஸ்ட்",
      "selectLanguage": "மொழியைத் தேர்ந்தெடுக்கவும்",
      "mediaPlayerApp": "மீடியா பிளேயர்",
      "noVideosFound": "வீடியோக்கள் எதுவும் இல்லை",
      "noAudioFileFound": "ஆடியோ கோப்புகள் எதுவும் இல்லை",
      "noFoldersFound": "கோப்புறைகள் எதுவும் இல்லை",
      "searchVideos": "வீடியோக்களைத் தேடுங்கள்...",
      "noResultFound": "முடிவுகள் எதுவும் இல்லை",
      "mb": "எம்பி",
      "yes": "ஆம்",
      "no": "இல்லை",
      "next": "அடுத்தது",
      "done": "முடிந்தது",
      "cancel": "ரத்து செய்",
      "submit": "சமர்ப்பி",
      "showDetailPage": "விவரப் பக்கத்தைக் காட்டு",
      "loading": "ஏற்றப்படுகிறது...",
      "deleteMedia": "மீடியாவை நீக்கு",
      "exitApp": "செயலியிலிருந்து வெளியேறவா?",
      "ohNoYouAreLeveApp": "ஓ இல்லை! இந்தச் செயலியை விட்டு வெளியேறுகிறீர்களா?",
      "showThumb500": "500 அளவு சிறுபடத்தைக் காட்டு",
      "howWouldYouLove": "இந்தச் செயலி உங்களுக்கு எப்படிப் பிடித்திருக்கிறது?",
      "areYouSureWantDeleteThisFile": "இந்தக் கோப்பை நிச்சயமாக நீக்க வேண்டுமா?",
      "searchAnything": "எதையும் தேடுங்கள்....",
      "deleteThisFile": "இந்தக் கோப்பை நீக்கவா?",
      "searchVideosAudios": "வீடியோக்கள் மற்றும் ஆடியோக்களைத் தேடுங்கள்",
      "noDataFound": "தரவு எதுவும் இல்லை",
      "orCreateNew": "அல்லது புதியதை உருவாக்கு",
      "enterName": "பெயரை உள்ளிடவும்",
      "add": "சேர்",
      "id": "ஐடி",
      "create": "உருவாக்கு",
      "modified": "மாற்றப்பட்டது",
      "orientation": "நோக்குநிலை",
      "size": "அளவு",
      "orientationSize": "நோக்குநிலை அளவு",
      "duration": "காலம்",
      "title": "தலைப்பு",
      "relativePath": "உறவினர் பாதை",
      "mimeType": "மைம் வகை",
      "rename": "பெயரை மாற்று",
      "selectExistingPlaylist": "தற்போதுள்ள பிளேலிஸ்ட்டைத் தேர்ந்தெடுக்கவும்",
      "choosePlaylist": "பிளேலிஸ்ட்டைத் தேர்வுசெய்க",
      "newPlaylistCreated": "புதிய பிளேலிஸ்ட் உருவாக்கப்பட்டது",
      "pleaseSelectEnterPlaylistName":
      "பிளேலிஸ்ட் பெயரைத் தேர்ந்தெடுக்கவும் அல்லது உள்ளிடவும்",
      "alreadyExistIn": "ஏற்கனவே இதில் உள்ளது:",
      "alreadyExists": "ஏற்கனவே உள்ளது",
      "addedTo": "இதில் சேர்க்கப்பட்டது:",
      "failedToDeleteFile": "கோப்பை நீக்க முடியவில்லை",
      "fileDeletedSuccessfully": "கோப்பு வெற்றிகரமாக நீக்கப்பட்டது",
      "errorSharingFile": "கோப்பைப் பகிர்வதில் பிழை",
      "fileCanNotBeLoaded": "பகிர்வதற்காக கோப்பை ஏற்ற முடியவில்லை",
      "fileNotFound": "கோப்பு கண்டறியப்படவில்லை",
      "sharing": "பகிர்கிறது:",
      "mediaFile": "ஊடகக் கோப்பு",
      "addedToFavourite": "விருப்பமானவற்றில் சேர்க்கப்பட்டது",
      "removedFromFavourites": "விருப்பமானவற்றிலிருந்து நீக்கப்பட்டது",
    },
    'ur': {
      'home': 'ہوم',
      'languageName': 'Urdu',
      'video': 'ویڈیو',
      'videos': 'ویڈیوز',
      'audio': 'آڈیو',
      'settings': 'ترتیبات',
      'theme': 'تھیم',
      'language': 'اردو',
      'chooseLanguage': 'زبان منتخب کریں',
      'selectPreferredLanguage': 'اپنی پسندیدہ زبان منتخب کریں۔',
      'welcome': 'خوش آمدید',
      'organize': 'ترتیب دیں',
      'skip': 'چھوڑیں',
      'favourite': 'پسندیدہ',
      'folder': 'فولڈر',
      'items': 'آئٹمز',
      'videMusicPlayer': 'ویڈیو اور میوزک پلیئر',
      'mediaPlayer': 'میڈیا پلیئر',
      'addToFavourite': 'پسندیدہ میں شامل کریں',
      'removeToFavourite': 'پسندیدہ سے ہٹائیں',
      'delete': 'حذف کریں',
      'share': 'شیئر کریں',
      'showDetail': 'تفصیل دکھائیں',
      'addToPlaylist': 'پلے لسٹ میں شامل کریں',
      'appTheme': 'ایپ تھیم',
      'preferredLanguage': 'پسندیدہ زبان',
      'shareTheApp': 'ایپ شیئر کریں',
      'rateTheApp': 'ایپ کی درجہ بندی کریں',
      'privacyPolicy': 'پرائیویسی پالیسی',
      "playlist": "پلے لسٹ",
      "selectLanguage": "زبان منتخب کریں",
      "mediaPlayerApp": "میڈیا پلیئر",
      "noVideosFound": "کوئی ویڈیو نہیں ملی",
      "noAudioFileFound": "کوئی آڈیو فائل نہیں ملی",
      "noFoldersFound": "کوئی فولڈر نہیں ملا",
      "searchVideos": "ویڈیو تلاش کریں...",
      "noResultFound": "کوئی نتیجہ نہیں ملا",
      "mb": "ایم بی",
      "yes": "جی ہاں",
      "no": "نہیں",
      "next": "اگلا",
      "done": "مکمل",
      "cancel": "منسوخ کریں",
      "submit": "جمع کریں",
      "showDetailPage": "تفصیلات کا صفحہ دکھائیں",
      "loading": "لوڈ ہو رہا ہے...",
      "deleteMedia": "میڈیا حذف کریں",
      "exitApp": "ایپ سے باہر نکلیں؟",
      "ohNoYouAreLeveApp": "اوہ نہیں! کیا آپ اس ایپلی کیشن کو چھوڑ رہے ہیں؟",
      "showThumb500": "500 سائز کا تھمب دکھائیں",
      "howWouldYouLove": "آپ کو یہ ایپ کیسی لگی؟",
      "areYouSureWantDeleteThisFile":
      "کیا آپ واقعی اس فائل کو حذف کرنا چاہتے ہیں؟",
      "searchAnything": "کچھ بھی تلاش کریں....",
      "deleteThisFile": "اس فائل کو حذف کریں؟",
      "searchVideosAudios": "ویڈیو اور آڈیو تلاش کریں",
      "noDataFound": "کوئی ڈیٹا نہیں ملا",
      "orCreateNew": "یا نیا بنائیں",
      "enterName": "نام درج کریں",
      "add": "شامل کریں",
      "id": "آئی ڈی",
      "create": "بنائیں",
      "modified": "ترمیم شدہ",
      "orientation": "رخ",
      "size": "سائز",
      "orientationSize": "واضح سائز",
      "duration": "دورانیہ",
      "title": "عنوان",
      "relativePath": "رشتہ دار راستہ",
      "mimeType": "مائم کی قسم",
      "rename": "نام تبدیل کریں",
      "selectExistingPlaylist": "موجودہ پلے لسٹ منتخب کریں",
      "choosePlaylist": "پلے لسٹ منتخب کریں",
      "newPlaylistCreated": "نئی پلے لسٹ بن گئی",
      "pleaseSelectEnterPlaylistName":
      "براہ کرم پلے لسٹ کا نام منتخب کریں یا درج کریں",
      "alreadyExistIn": "پہلے سے موجود ہے میں",
      "alreadyExists": "پہلے سے موجود ہے",
      "addedTo": "میں شامل کر دیا گیا",
      "failedToDeleteFile": "فائل حذف کرنے میں ناکامی",
      "fileDeletedSuccessfully": "فائل کامیابی سے حذف ہو گئی",
      "errorSharingFile": "فائل شیئر کرنے میں خرابی",
      "fileCanNotBeLoaded": "شیئر کرنے کے لیے فائل لوڈ نہیں ہو سکتی",
      "fileNotFound": "فائل نہیں ملی",
      "sharing": "شیئرنگ:",
      "mediaFile": "میڈیا فائل",
      "addedToFavourite": "پسندیدہ میں شامل کر دیا گیا",
      "removedFromFavourites": "پسندیدہ سے ہٹا دیا گیا",
    },
  };

  String tr(String key) =>
      translations[locale.languageCode]?[key] ??
          translations['en']![key] ??
          key;

  static const LocalizationsDelegate<AppStrings> delegate = _AppLocDelegate();

  static String get(BuildContext context, String key) {
    final locale = Localizations.localeOf(context).languageCode;
    return translations[locale]?[key] ?? translations['en']![key] ?? key;
  }
}

class _AppLocDelegate extends LocalizationsDelegate<AppStrings> {
  const _AppLocDelegate();

  @override
  bool isSupported(Locale locale) =>
      AppStrings.translations.keys.contains(locale.languageCode);

  @override
  Future<AppStrings> load(Locale locale) async {
    return AppStrings(locale);
  }

  @override
  bool shouldReload(_AppLocDelegate old) => false;
}